// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package com.futu.openapi.pb;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   *返回结果
   * </pre>
   *
   * Protobuf enum {@code Common.RetType}
   */
  public enum RetType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>RetType_Succeed = 0;</code>
     */
    RetType_Succeed(0),
    /**
     * <pre>
     *失败
     * </pre>
     *
     * <code>RetType_Failed = -1;</code>
     */
    RetType_Failed(-1),
    /**
     * <pre>
     *超时
     * </pre>
     *
     * <code>RetType_TimeOut = -100;</code>
     */
    RetType_TimeOut(-100),
    /**
     * <pre>
     *连接断开
     * </pre>
     *
     * <code>RetType_DisConnect = -200;</code>
     */
    RetType_DisConnect(-200),
    /**
     * <pre>
     *未知结果
     * </pre>
     *
     * <code>RetType_Unknown = -400;</code>
     */
    RetType_Unknown(-400),
    /**
     * <pre>
     *包内容非法
     * </pre>
     *
     * <code>RetType_Invalid = -500;</code>
     */
    RetType_Invalid(-500),
    ;

    /**
     * <pre>
     *成功
     * </pre>
     *
     * <code>RetType_Succeed = 0;</code>
     */
    public static final int RetType_Succeed_VALUE = 0;
    /**
     * <pre>
     *失败
     * </pre>
     *
     * <code>RetType_Failed = -1;</code>
     */
    public static final int RetType_Failed_VALUE = -1;
    /**
     * <pre>
     *超时
     * </pre>
     *
     * <code>RetType_TimeOut = -100;</code>
     */
    public static final int RetType_TimeOut_VALUE = -100;
    /**
     * <pre>
     *连接断开
     * </pre>
     *
     * <code>RetType_DisConnect = -200;</code>
     */
    public static final int RetType_DisConnect_VALUE = -200;
    /**
     * <pre>
     *未知结果
     * </pre>
     *
     * <code>RetType_Unknown = -400;</code>
     */
    public static final int RetType_Unknown_VALUE = -400;
    /**
     * <pre>
     *包内容非法
     * </pre>
     *
     * <code>RetType_Invalid = -500;</code>
     */
    public static final int RetType_Invalid_VALUE = -500;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static RetType valueOf(int value) {
      return forNumber(value);
    }

    public static RetType forNumber(int value) {
      switch (value) {
        case 0: return RetType_Succeed;
        case -1: return RetType_Failed;
        case -100: return RetType_TimeOut;
        case -200: return RetType_DisConnect;
        case -400: return RetType_Unknown;
        case -500: return RetType_Invalid;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RetType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RetType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RetType>() {
            public RetType findValueByNumber(int number) {
              return RetType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futu.openapi.pb.Common.getDescriptor().getEnumTypes().get(0);
    }

    private static final RetType[] VALUES = values();

    public static RetType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private RetType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Common.RetType)
  }

  /**
   * <pre>
   *包加密算法
   * </pre>
   *
   * Protobuf enum {@code Common.PacketEncAlgo}
   */
  public enum PacketEncAlgo
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *富途修改过的AES的ECB加密模式
     * </pre>
     *
     * <code>PacketEncAlgo_FTAES_ECB = 0;</code>
     */
    PacketEncAlgo_FTAES_ECB(0),
    /**
     * <pre>
     *不加密
     * </pre>
     *
     * <code>PacketEncAlgo_None = -1;</code>
     */
    PacketEncAlgo_None(-1),
    /**
     * <pre>
     *标准的AES的ECB加密模式
     * </pre>
     *
     * <code>PacketEncAlgo_AES_ECB = 1;</code>
     */
    PacketEncAlgo_AES_ECB(1),
    /**
     * <pre>
     *标准的AES的CBC加密模式
     * </pre>
     *
     * <code>PacketEncAlgo_AES_CBC = 2;</code>
     */
    PacketEncAlgo_AES_CBC(2),
    ;

    /**
     * <pre>
     *富途修改过的AES的ECB加密模式
     * </pre>
     *
     * <code>PacketEncAlgo_FTAES_ECB = 0;</code>
     */
    public static final int PacketEncAlgo_FTAES_ECB_VALUE = 0;
    /**
     * <pre>
     *不加密
     * </pre>
     *
     * <code>PacketEncAlgo_None = -1;</code>
     */
    public static final int PacketEncAlgo_None_VALUE = -1;
    /**
     * <pre>
     *标准的AES的ECB加密模式
     * </pre>
     *
     * <code>PacketEncAlgo_AES_ECB = 1;</code>
     */
    public static final int PacketEncAlgo_AES_ECB_VALUE = 1;
    /**
     * <pre>
     *标准的AES的CBC加密模式
     * </pre>
     *
     * <code>PacketEncAlgo_AES_CBC = 2;</code>
     */
    public static final int PacketEncAlgo_AES_CBC_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PacketEncAlgo valueOf(int value) {
      return forNumber(value);
    }

    public static PacketEncAlgo forNumber(int value) {
      switch (value) {
        case 0: return PacketEncAlgo_FTAES_ECB;
        case -1: return PacketEncAlgo_None;
        case 1: return PacketEncAlgo_AES_ECB;
        case 2: return PacketEncAlgo_AES_CBC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PacketEncAlgo>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PacketEncAlgo> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PacketEncAlgo>() {
            public PacketEncAlgo findValueByNumber(int number) {
              return PacketEncAlgo.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futu.openapi.pb.Common.getDescriptor().getEnumTypes().get(1);
    }

    private static final PacketEncAlgo[] VALUES = values();

    public static PacketEncAlgo valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PacketEncAlgo(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Common.PacketEncAlgo)
  }

  /**
   * <pre>
   *协议格式，请求协议在请求头中指定，推送协议在Init时指定
   * </pre>
   *
   * Protobuf enum {@code Common.ProtoFmt}
   */
  public enum ProtoFmt
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *Google Protobuf格式
     * </pre>
     *
     * <code>ProtoFmt_Protobuf = 0;</code>
     */
    ProtoFmt_Protobuf(0),
    /**
     * <pre>
     *Json格式
     * </pre>
     *
     * <code>ProtoFmt_Json = 1;</code>
     */
    ProtoFmt_Json(1),
    ;

    /**
     * <pre>
     *Google Protobuf格式
     * </pre>
     *
     * <code>ProtoFmt_Protobuf = 0;</code>
     */
    public static final int ProtoFmt_Protobuf_VALUE = 0;
    /**
     * <pre>
     *Json格式
     * </pre>
     *
     * <code>ProtoFmt_Json = 1;</code>
     */
    public static final int ProtoFmt_Json_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProtoFmt valueOf(int value) {
      return forNumber(value);
    }

    public static ProtoFmt forNumber(int value) {
      switch (value) {
        case 0: return ProtoFmt_Protobuf;
        case 1: return ProtoFmt_Json;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProtoFmt>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProtoFmt> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProtoFmt>() {
            public ProtoFmt findValueByNumber(int number) {
              return ProtoFmt.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futu.openapi.pb.Common.getDescriptor().getEnumTypes().get(2);
    }

    private static final ProtoFmt[] VALUES = values();

    public static ProtoFmt valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProtoFmt(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Common.ProtoFmt)
  }

  /**
   * <pre>
   *用户注册归属地
   * </pre>
   *
   * Protobuf enum {@code Common.UserAttribution}
   */
  public enum UserAttribution
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * </pre>
     *
     * <code>UserAttribution_Unknown = 0;</code>
     */
    UserAttribution_Unknown(0),
    /**
     * <pre>
     *牛牛
     * </pre>
     *
     * <code>UserAttribution_NN = 1;</code>
     */
    UserAttribution_NN(1),
    /**
     * <pre>
     *MooMoo
     * </pre>
     *
     * <code>UserAttribution_MM = 2;</code>
     */
    UserAttribution_MM(2),
    /**
     * <pre>
     *新加坡
     * </pre>
     *
     * <code>UserAttribution_SG = 3;</code>
     */
    UserAttribution_SG(3),
    ;

    /**
     * <pre>
     * </pre>
     *
     * <code>UserAttribution_Unknown = 0;</code>
     */
    public static final int UserAttribution_Unknown_VALUE = 0;
    /**
     * <pre>
     *牛牛
     * </pre>
     *
     * <code>UserAttribution_NN = 1;</code>
     */
    public static final int UserAttribution_NN_VALUE = 1;
    /**
     * <pre>
     *MooMoo
     * </pre>
     *
     * <code>UserAttribution_MM = 2;</code>
     */
    public static final int UserAttribution_MM_VALUE = 2;
    /**
     * <pre>
     *新加坡
     * </pre>
     *
     * <code>UserAttribution_SG = 3;</code>
     */
    public static final int UserAttribution_SG_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UserAttribution valueOf(int value) {
      return forNumber(value);
    }

    public static UserAttribution forNumber(int value) {
      switch (value) {
        case 0: return UserAttribution_Unknown;
        case 1: return UserAttribution_NN;
        case 2: return UserAttribution_MM;
        case 3: return UserAttribution_SG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UserAttribution>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UserAttribution> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UserAttribution>() {
            public UserAttribution findValueByNumber(int number) {
              return UserAttribution.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futu.openapi.pb.Common.getDescriptor().getEnumTypes().get(3);
    }

    private static final UserAttribution[] VALUES = values();

    public static UserAttribution valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UserAttribution(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Common.UserAttribution)
  }

  /**
   * Protobuf enum {@code Common.ProgramStatusType}
   */
  public enum ProgramStatusType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ProgramStatusType_None = 0;</code>
     */
    ProgramStatusType_None(0),
    /**
     * <pre>
     *已完成类似加载配置,启动服务器等操作,服务器启动之前的状态无需返回
     * </pre>
     *
     * <code>ProgramStatusType_Loaded = 1;</code>
     */
    ProgramStatusType_Loaded(1),
    /**
     * <pre>
     *登录中
     * </pre>
     *
     * <code>ProgramStatusType_Loging = 2;</code>
     */
    ProgramStatusType_Loging(2),
    /**
     * <pre>
     *需要图形验证码
     * </pre>
     *
     * <code>ProgramStatusType_NeedPicVerifyCode = 3;</code>
     */
    ProgramStatusType_NeedPicVerifyCode(3),
    /**
     * <pre>
     *需要手机验证码
     * </pre>
     *
     * <code>ProgramStatusType_NeedPhoneVerifyCode = 4;</code>
     */
    ProgramStatusType_NeedPhoneVerifyCode(4),
    /**
     * <pre>
     *登录失败,详细原因在描述返回
     * </pre>
     *
     * <code>ProgramStatusType_LoginFailed = 5;</code>
     */
    ProgramStatusType_LoginFailed(5),
    /**
     * <pre>
     *客户端版本过低
     * </pre>
     *
     * <code>ProgramStatusType_ForceUpdate = 6;</code>
     */
    ProgramStatusType_ForceUpdate(6),
    /**
     * <pre>
     *正在拉取类似免责声明等一些必要信息
     * </pre>
     *
     * <code>ProgramStatusType_NessaryDataPreparing = 7;</code>
     */
    ProgramStatusType_NessaryDataPreparing(7),
    /**
     * <pre>
     *缺少必要信息
     * </pre>
     *
     * <code>ProgramStatusType_NessaryDataMissing = 8;</code>
     */
    ProgramStatusType_NessaryDataMissing(8),
    /**
     * <pre>
     *未同意免责声明
     * </pre>
     *
     * <code>ProgramStatusType_UnAgreeDisclaimer = 9;</code>
     */
    ProgramStatusType_UnAgreeDisclaimer(9),
    /**
     * <pre>
     *可以接收业务协议收发,正常可用状态
     * </pre>
     *
     * <code>ProgramStatusType_Ready = 10;</code>
     */
    ProgramStatusType_Ready(10),
    /**
     * <pre>
     *OpenD登录后被强制退出登录，会导致连接全部断开,需要重连后才能得到以下该状态（并且需要在ui模式下）
     * </pre>
     *
     * <code>ProgramStatusType_ForceLogout = 11;</code>
     */
    ProgramStatusType_ForceLogout(11),
    /**
     * <pre>
     *拉取免责声明标志失败
     * </pre>
     *
     * <code>ProgramStatusType_DisclaimerPullFailed = 12;</code>
     */
    ProgramStatusType_DisclaimerPullFailed(12),
    ;

    /**
     * <code>ProgramStatusType_None = 0;</code>
     */
    public static final int ProgramStatusType_None_VALUE = 0;
    /**
     * <pre>
     *已完成类似加载配置,启动服务器等操作,服务器启动之前的状态无需返回
     * </pre>
     *
     * <code>ProgramStatusType_Loaded = 1;</code>
     */
    public static final int ProgramStatusType_Loaded_VALUE = 1;
    /**
     * <pre>
     *登录中
     * </pre>
     *
     * <code>ProgramStatusType_Loging = 2;</code>
     */
    public static final int ProgramStatusType_Loging_VALUE = 2;
    /**
     * <pre>
     *需要图形验证码
     * </pre>
     *
     * <code>ProgramStatusType_NeedPicVerifyCode = 3;</code>
     */
    public static final int ProgramStatusType_NeedPicVerifyCode_VALUE = 3;
    /**
     * <pre>
     *需要手机验证码
     * </pre>
     *
     * <code>ProgramStatusType_NeedPhoneVerifyCode = 4;</code>
     */
    public static final int ProgramStatusType_NeedPhoneVerifyCode_VALUE = 4;
    /**
     * <pre>
     *登录失败,详细原因在描述返回
     * </pre>
     *
     * <code>ProgramStatusType_LoginFailed = 5;</code>
     */
    public static final int ProgramStatusType_LoginFailed_VALUE = 5;
    /**
     * <pre>
     *客户端版本过低
     * </pre>
     *
     * <code>ProgramStatusType_ForceUpdate = 6;</code>
     */
    public static final int ProgramStatusType_ForceUpdate_VALUE = 6;
    /**
     * <pre>
     *正在拉取类似免责声明等一些必要信息
     * </pre>
     *
     * <code>ProgramStatusType_NessaryDataPreparing = 7;</code>
     */
    public static final int ProgramStatusType_NessaryDataPreparing_VALUE = 7;
    /**
     * <pre>
     *缺少必要信息
     * </pre>
     *
     * <code>ProgramStatusType_NessaryDataMissing = 8;</code>
     */
    public static final int ProgramStatusType_NessaryDataMissing_VALUE = 8;
    /**
     * <pre>
     *未同意免责声明
     * </pre>
     *
     * <code>ProgramStatusType_UnAgreeDisclaimer = 9;</code>
     */
    public static final int ProgramStatusType_UnAgreeDisclaimer_VALUE = 9;
    /**
     * <pre>
     *可以接收业务协议收发,正常可用状态
     * </pre>
     *
     * <code>ProgramStatusType_Ready = 10;</code>
     */
    public static final int ProgramStatusType_Ready_VALUE = 10;
    /**
     * <pre>
     *OpenD登录后被强制退出登录，会导致连接全部断开,需要重连后才能得到以下该状态（并且需要在ui模式下）
     * </pre>
     *
     * <code>ProgramStatusType_ForceLogout = 11;</code>
     */
    public static final int ProgramStatusType_ForceLogout_VALUE = 11;
    /**
     * <pre>
     *拉取免责声明标志失败
     * </pre>
     *
     * <code>ProgramStatusType_DisclaimerPullFailed = 12;</code>
     */
    public static final int ProgramStatusType_DisclaimerPullFailed_VALUE = 12;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ProgramStatusType valueOf(int value) {
      return forNumber(value);
    }

    public static ProgramStatusType forNumber(int value) {
      switch (value) {
        case 0: return ProgramStatusType_None;
        case 1: return ProgramStatusType_Loaded;
        case 2: return ProgramStatusType_Loging;
        case 3: return ProgramStatusType_NeedPicVerifyCode;
        case 4: return ProgramStatusType_NeedPhoneVerifyCode;
        case 5: return ProgramStatusType_LoginFailed;
        case 6: return ProgramStatusType_ForceUpdate;
        case 7: return ProgramStatusType_NessaryDataPreparing;
        case 8: return ProgramStatusType_NessaryDataMissing;
        case 9: return ProgramStatusType_UnAgreeDisclaimer;
        case 10: return ProgramStatusType_Ready;
        case 11: return ProgramStatusType_ForceLogout;
        case 12: return ProgramStatusType_DisclaimerPullFailed;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProgramStatusType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProgramStatusType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProgramStatusType>() {
            public ProgramStatusType findValueByNumber(int number) {
              return ProgramStatusType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futu.openapi.pb.Common.getDescriptor().getEnumTypes().get(4);
    }

    private static final ProgramStatusType[] VALUES = values();

    public static ProgramStatusType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ProgramStatusType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Common.ProgramStatusType)
  }

  public interface PacketIDOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.PacketID)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
     * </pre>
     *
     * <code>required uint64 connID = 1;</code>
     */
    boolean hasConnID();
    /**
     * <pre>
     *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
     * </pre>
     *
     * <code>required uint64 connID = 1;</code>
     */
    long getConnID();

    /**
     * <pre>
     *自增序列号
     * </pre>
     *
     * <code>required uint32 serialNo = 2;</code>
     */
    boolean hasSerialNo();
    /**
     * <pre>
     *自增序列号
     * </pre>
     *
     * <code>required uint32 serialNo = 2;</code>
     */
    int getSerialNo();
  }
  /**
   * <pre>
   *包的唯一标识，用于回放攻击的识别和保护
   * </pre>
   *
   * Protobuf type {@code Common.PacketID}
   */
  public  static final class PacketID extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Common.PacketID)
      PacketIDOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PacketID.newBuilder() to construct.
    private PacketID(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PacketID() {
      connID_ = 0L;
      serialNo_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PacketID(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              connID_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              serialNo_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.openapi.pb.Common.internal_static_Common_PacketID_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.openapi.pb.Common.internal_static_Common_PacketID_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.openapi.pb.Common.PacketID.class, com.futu.openapi.pb.Common.PacketID.Builder.class);
    }

    private int bitField0_;
    public static final int CONNID_FIELD_NUMBER = 1;
    private long connID_;
    /**
     * <pre>
     *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
     * </pre>
     *
     * <code>required uint64 connID = 1;</code>
     */
    public boolean hasConnID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
     * </pre>
     *
     * <code>required uint64 connID = 1;</code>
     */
    public long getConnID() {
      return connID_;
    }

    public static final int SERIALNO_FIELD_NUMBER = 2;
    private int serialNo_;
    /**
     * <pre>
     *自增序列号
     * </pre>
     *
     * <code>required uint32 serialNo = 2;</code>
     */
    public boolean hasSerialNo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *自增序列号
     * </pre>
     *
     * <code>required uint32 serialNo = 2;</code>
     */
    public int getSerialNo() {
      return serialNo_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasConnID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSerialNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, connID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, serialNo_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, connID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, serialNo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.futu.openapi.pb.Common.PacketID)) {
        return super.equals(obj);
      }
      com.futu.openapi.pb.Common.PacketID other = (com.futu.openapi.pb.Common.PacketID) obj;

      boolean result = true;
      result = result && (hasConnID() == other.hasConnID());
      if (hasConnID()) {
        result = result && (getConnID()
            == other.getConnID());
      }
      result = result && (hasSerialNo() == other.hasSerialNo());
      if (hasSerialNo()) {
        result = result && (getSerialNo()
            == other.getSerialNo());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConnID()) {
        hash = (37 * hash) + CONNID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getConnID());
      }
      if (hasSerialNo()) {
        hash = (37 * hash) + SERIALNO_FIELD_NUMBER;
        hash = (53 * hash) + getSerialNo();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.futu.openapi.pb.Common.PacketID parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.Common.PacketID parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.Common.PacketID parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.Common.PacketID parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.Common.PacketID parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.Common.PacketID parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.Common.PacketID parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.Common.PacketID parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.Common.PacketID parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.Common.PacketID parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.Common.PacketID parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.Common.PacketID parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.futu.openapi.pb.Common.PacketID prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *包的唯一标识，用于回放攻击的识别和保护
     * </pre>
     *
     * Protobuf type {@code Common.PacketID}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.PacketID)
        com.futu.openapi.pb.Common.PacketIDOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.openapi.pb.Common.internal_static_Common_PacketID_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.openapi.pb.Common.internal_static_Common_PacketID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.openapi.pb.Common.PacketID.class, com.futu.openapi.pb.Common.PacketID.Builder.class);
      }

      // Construct using com.futu.openapi.pb.Common.PacketID.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        connID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        serialNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.openapi.pb.Common.internal_static_Common_PacketID_descriptor;
      }

      public com.futu.openapi.pb.Common.PacketID getDefaultInstanceForType() {
        return com.futu.openapi.pb.Common.PacketID.getDefaultInstance();
      }

      public com.futu.openapi.pb.Common.PacketID build() {
        com.futu.openapi.pb.Common.PacketID result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.openapi.pb.Common.PacketID buildPartial() {
        com.futu.openapi.pb.Common.PacketID result = new com.futu.openapi.pb.Common.PacketID(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.connID_ = connID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.serialNo_ = serialNo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.openapi.pb.Common.PacketID) {
          return mergeFrom((com.futu.openapi.pb.Common.PacketID)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.openapi.pb.Common.PacketID other) {
        if (other == com.futu.openapi.pb.Common.PacketID.getDefaultInstance()) return this;
        if (other.hasConnID()) {
          setConnID(other.getConnID());
        }
        if (other.hasSerialNo()) {
          setSerialNo(other.getSerialNo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasConnID()) {
          return false;
        }
        if (!hasSerialNo()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.openapi.pb.Common.PacketID parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.openapi.pb.Common.PacketID) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long connID_ ;
      /**
       * <pre>
       *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
       * </pre>
       *
       * <code>required uint64 connID = 1;</code>
       */
      public boolean hasConnID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
       * </pre>
       *
       * <code>required uint64 connID = 1;</code>
       */
      public long getConnID() {
        return connID_;
      }
      /**
       * <pre>
       *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
       * </pre>
       *
       * <code>required uint64 connID = 1;</code>
       */
      public Builder setConnID(long value) {
        bitField0_ |= 0x00000001;
        connID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前TCP连接的连接ID，一条连接的唯一标识，InitConnect协议会返回
       * </pre>
       *
       * <code>required uint64 connID = 1;</code>
       */
      public Builder clearConnID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        connID_ = 0L;
        onChanged();
        return this;
      }

      private int serialNo_ ;
      /**
       * <pre>
       *自增序列号
       * </pre>
       *
       * <code>required uint32 serialNo = 2;</code>
       */
      public boolean hasSerialNo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *自增序列号
       * </pre>
       *
       * <code>required uint32 serialNo = 2;</code>
       */
      public int getSerialNo() {
        return serialNo_;
      }
      /**
       * <pre>
       *自增序列号
       * </pre>
       *
       * <code>required uint32 serialNo = 2;</code>
       */
      public Builder setSerialNo(int value) {
        bitField0_ |= 0x00000002;
        serialNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自增序列号
       * </pre>
       *
       * <code>required uint32 serialNo = 2;</code>
       */
      public Builder clearSerialNo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serialNo_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Common.PacketID)
    }

    // @@protoc_insertion_point(class_scope:Common.PacketID)
    private static final com.futu.openapi.pb.Common.PacketID DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.futu.openapi.pb.Common.PacketID();
    }

    public static com.futu.openapi.pb.Common.PacketID getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PacketID>
        PARSER = new com.google.protobuf.AbstractParser<PacketID>() {
      public PacketID parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PacketID(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PacketID> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PacketID> getParserForType() {
      return PARSER;
    }

    public com.futu.openapi.pb.Common.PacketID getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProgramStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Common.ProgramStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *当前状态
     * </pre>
     *
     * <code>required .Common.ProgramStatusType type = 1;</code>
     */
    boolean hasType();
    /**
     * <pre>
     *当前状态
     * </pre>
     *
     * <code>required .Common.ProgramStatusType type = 1;</code>
     */
    com.futu.openapi.pb.Common.ProgramStatusType getType();

    /**
     * <pre>
     * 额外描述
     * </pre>
     *
     * <code>optional string strExtDesc = 2;</code>
     */
    boolean hasStrExtDesc();
    /**
     * <pre>
     * 额外描述
     * </pre>
     *
     * <code>optional string strExtDesc = 2;</code>
     */
    java.lang.String getStrExtDesc();
    /**
     * <pre>
     * 额外描述
     * </pre>
     *
     * <code>optional string strExtDesc = 2;</code>
     */
    com.google.protobuf.ByteString
        getStrExtDescBytes();
  }
  /**
   * Protobuf type {@code Common.ProgramStatus}
   */
  public  static final class ProgramStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Common.ProgramStatus)
      ProgramStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProgramStatus.newBuilder() to construct.
    private ProgramStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProgramStatus() {
      type_ = 0;
      strExtDesc_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProgramStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.futu.openapi.pb.Common.ProgramStatusType value = com.futu.openapi.pb.Common.ProgramStatusType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = rawValue;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              strExtDesc_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.openapi.pb.Common.internal_static_Common_ProgramStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.openapi.pb.Common.internal_static_Common_ProgramStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.openapi.pb.Common.ProgramStatus.class, com.futu.openapi.pb.Common.ProgramStatus.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     *当前状态
     * </pre>
     *
     * <code>required .Common.ProgramStatusType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *当前状态
     * </pre>
     *
     * <code>required .Common.ProgramStatusType type = 1;</code>
     */
    public com.futu.openapi.pb.Common.ProgramStatusType getType() {
      com.futu.openapi.pb.Common.ProgramStatusType result = com.futu.openapi.pb.Common.ProgramStatusType.valueOf(type_);
      return result == null ? com.futu.openapi.pb.Common.ProgramStatusType.ProgramStatusType_None : result;
    }

    public static final int STREXTDESC_FIELD_NUMBER = 2;
    private volatile java.lang.Object strExtDesc_;
    /**
     * <pre>
     * 额外描述
     * </pre>
     *
     * <code>optional string strExtDesc = 2;</code>
     */
    public boolean hasStrExtDesc() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * 额外描述
     * </pre>
     *
     * <code>optional string strExtDesc = 2;</code>
     */
    public java.lang.String getStrExtDesc() {
      java.lang.Object ref = strExtDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          strExtDesc_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * 额外描述
     * </pre>
     *
     * <code>optional string strExtDesc = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStrExtDescBytes() {
      java.lang.Object ref = strExtDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strExtDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, strExtDesc_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, strExtDesc_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.futu.openapi.pb.Common.ProgramStatus)) {
        return super.equals(obj);
      }
      com.futu.openapi.pb.Common.ProgramStatus other = (com.futu.openapi.pb.Common.ProgramStatus) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && type_ == other.type_;
      }
      result = result && (hasStrExtDesc() == other.hasStrExtDesc());
      if (hasStrExtDesc()) {
        result = result && getStrExtDesc()
            .equals(other.getStrExtDesc());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasStrExtDesc()) {
        hash = (37 * hash) + STREXTDESC_FIELD_NUMBER;
        hash = (53 * hash) + getStrExtDesc().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.futu.openapi.pb.Common.ProgramStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.Common.ProgramStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.futu.openapi.pb.Common.ProgramStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Common.ProgramStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Common.ProgramStatus)
        com.futu.openapi.pb.Common.ProgramStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.openapi.pb.Common.internal_static_Common_ProgramStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.openapi.pb.Common.internal_static_Common_ProgramStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.openapi.pb.Common.ProgramStatus.class, com.futu.openapi.pb.Common.ProgramStatus.Builder.class);
      }

      // Construct using com.futu.openapi.pb.Common.ProgramStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        strExtDesc_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.openapi.pb.Common.internal_static_Common_ProgramStatus_descriptor;
      }

      public com.futu.openapi.pb.Common.ProgramStatus getDefaultInstanceForType() {
        return com.futu.openapi.pb.Common.ProgramStatus.getDefaultInstance();
      }

      public com.futu.openapi.pb.Common.ProgramStatus build() {
        com.futu.openapi.pb.Common.ProgramStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.openapi.pb.Common.ProgramStatus buildPartial() {
        com.futu.openapi.pb.Common.ProgramStatus result = new com.futu.openapi.pb.Common.ProgramStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.strExtDesc_ = strExtDesc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.openapi.pb.Common.ProgramStatus) {
          return mergeFrom((com.futu.openapi.pb.Common.ProgramStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.openapi.pb.Common.ProgramStatus other) {
        if (other == com.futu.openapi.pb.Common.ProgramStatus.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasStrExtDesc()) {
          bitField0_ |= 0x00000002;
          strExtDesc_ = other.strExtDesc_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.openapi.pb.Common.ProgramStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.openapi.pb.Common.ProgramStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <pre>
       *当前状态
       * </pre>
       *
       * <code>required .Common.ProgramStatusType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *当前状态
       * </pre>
       *
       * <code>required .Common.ProgramStatusType type = 1;</code>
       */
      public com.futu.openapi.pb.Common.ProgramStatusType getType() {
        com.futu.openapi.pb.Common.ProgramStatusType result = com.futu.openapi.pb.Common.ProgramStatusType.valueOf(type_);
        return result == null ? com.futu.openapi.pb.Common.ProgramStatusType.ProgramStatusType_None : result;
      }
      /**
       * <pre>
       *当前状态
       * </pre>
       *
       * <code>required .Common.ProgramStatusType type = 1;</code>
       */
      public Builder setType(com.futu.openapi.pb.Common.ProgramStatusType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前状态
       * </pre>
       *
       * <code>required .Common.ProgramStatusType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object strExtDesc_ = "";
      /**
       * <pre>
       * 额外描述
       * </pre>
       *
       * <code>optional string strExtDesc = 2;</code>
       */
      public boolean hasStrExtDesc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * 额外描述
       * </pre>
       *
       * <code>optional string strExtDesc = 2;</code>
       */
      public java.lang.String getStrExtDesc() {
        java.lang.Object ref = strExtDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            strExtDesc_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 额外描述
       * </pre>
       *
       * <code>optional string strExtDesc = 2;</code>
       */
      public com.google.protobuf.ByteString
          getStrExtDescBytes() {
        java.lang.Object ref = strExtDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strExtDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 额外描述
       * </pre>
       *
       * <code>optional string strExtDesc = 2;</code>
       */
      public Builder setStrExtDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        strExtDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 额外描述
       * </pre>
       *
       * <code>optional string strExtDesc = 2;</code>
       */
      public Builder clearStrExtDesc() {
        bitField0_ = (bitField0_ & ~0x00000002);
        strExtDesc_ = getDefaultInstance().getStrExtDesc();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 额外描述
       * </pre>
       *
       * <code>optional string strExtDesc = 2;</code>
       */
      public Builder setStrExtDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        strExtDesc_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Common.ProgramStatus)
    }

    // @@protoc_insertion_point(class_scope:Common.ProgramStatus)
    private static final com.futu.openapi.pb.Common.ProgramStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.futu.openapi.pb.Common.ProgramStatus();
    }

    public static com.futu.openapi.pb.Common.ProgramStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProgramStatus>
        PARSER = new com.google.protobuf.AbstractParser<ProgramStatus>() {
      public ProgramStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProgramStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProgramStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProgramStatus> getParserForType() {
      return PARSER;
    }

    public com.futu.openapi.pb.Common.ProgramStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Common_PacketID_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Common_PacketID_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Common_ProgramStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Common_ProgramStatus_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Common.proto\022\006Common\",\n\010PacketID\022\016\n\006co" +
      "nnID\030\001 \002(\004\022\020\n\010serialNo\030\002 \002(\r\"L\n\rProgramS" +
      "tatus\022\'\n\004type\030\001 \002(\0162\031.Common.ProgramStat" +
      "usType\022\022\n\nstrExtDesc\030\002 \001(\t*\266\001\n\007RetType\022\023" +
      "\n\017RetType_Succeed\020\000\022\033\n\016RetType_Failed\020\377\377" +
      "\377\377\377\377\377\377\377\001\022\034\n\017RetType_TimeOut\020\234\377\377\377\377\377\377\377\377\001\022\037" +
      "\n\022RetType_DisConnect\020\270\376\377\377\377\377\377\377\377\001\022\034\n\017RetTy" +
      "pe_Unknown\020\360\374\377\377\377\377\377\377\377\001\022\034\n\017RetType_Invalid" +
      "\020\214\374\377\377\377\377\377\377\377\001*\203\001\n\rPacketEncAlgo\022\033\n\027PacketE" +
      "ncAlgo_FTAES_ECB\020\000\022\037\n\022PacketEncAlgo_None" +
      "\020\377\377\377\377\377\377\377\377\377\001\022\031\n\025PacketEncAlgo_AES_ECB\020\001\022\031" +
      "\n\025PacketEncAlgo_AES_CBC\020\002*4\n\010ProtoFmt\022\025\n" +
      "\021ProtoFmt_Protobuf\020\000\022\021\n\rProtoFmt_Json\020\001*" +
      "v\n\017UserAttribution\022\033\n\027UserAttribution_Un" +
      "known\020\000\022\026\n\022UserAttribution_NN\020\001\022\026\n\022UserA" +
      "ttribution_MM\020\002\022\026\n\022UserAttribution_SG\020\003*" +
      "\360\003\n\021ProgramStatusType\022\032\n\026ProgramStatusTy" +
      "pe_None\020\000\022\034\n\030ProgramStatusType_Loaded\020\001\022" +
      "\034\n\030ProgramStatusType_Loging\020\002\022\'\n#Program" +
      "StatusType_NeedPicVerifyCode\020\003\022)\n%Progra" +
      "mStatusType_NeedPhoneVerifyCode\020\004\022!\n\035Pro" +
      "gramStatusType_LoginFailed\020\005\022!\n\035ProgramS" +
      "tatusType_ForceUpdate\020\006\022*\n&ProgramStatus" +
      "Type_NessaryDataPreparing\020\007\022(\n$ProgramSt" +
      "atusType_NessaryDataMissing\020\010\022\'\n#Program" +
      "StatusType_UnAgreeDisclaimer\020\t\022\033\n\027Progra" +
      "mStatusType_Ready\020\n\022!\n\035ProgramStatusType" +
      "_ForceLogout\020\013\022*\n&ProgramStatusType_Disc" +
      "laimerPullFailed\020\014B=\n\023com.futu.openapi.p" +
      "bZ&github.com/futuopen/ftapi4go/pb/commo" +
      "n"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Common_PacketID_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Common_PacketID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Common_PacketID_descriptor,
        new java.lang.String[] { "ConnID", "SerialNo", });
    internal_static_Common_ProgramStatus_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Common_ProgramStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Common_ProgramStatus_descriptor,
        new java.lang.String[] { "Type", "StrExtDesc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
