// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qot_UpdateBroker.proto

package com.futu.openapi.pb;

public final class QotUpdateBroker {
  private QotUpdateBroker() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateBroker.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    boolean hasSecurity();
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    com.futu.openapi.pb.QotCommon.Security getSecurity();
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    com.futu.openapi.pb.QotCommon.SecurityOrBuilder getSecurityOrBuilder();

    /**
     * <pre>
     *经纪Ask(卖)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
     */
    java.util.List<com.futu.openapi.pb.QotCommon.Broker> 
        getBrokerAskListList();
    /**
     * <pre>
     *经纪Ask(卖)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
     */
    com.futu.openapi.pb.QotCommon.Broker getBrokerAskList(int index);
    /**
     * <pre>
     *经纪Ask(卖)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
     */
    int getBrokerAskListCount();
    /**
     * <pre>
     *经纪Ask(卖)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
     */
    java.util.List<? extends com.futu.openapi.pb.QotCommon.BrokerOrBuilder> 
        getBrokerAskListOrBuilderList();
    /**
     * <pre>
     *经纪Ask(卖)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
     */
    com.futu.openapi.pb.QotCommon.BrokerOrBuilder getBrokerAskListOrBuilder(
        int index);

    /**
     * <pre>
     *经纪Bid(买)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
     */
    java.util.List<com.futu.openapi.pb.QotCommon.Broker> 
        getBrokerBidListList();
    /**
     * <pre>
     *经纪Bid(买)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
     */
    com.futu.openapi.pb.QotCommon.Broker getBrokerBidList(int index);
    /**
     * <pre>
     *经纪Bid(买)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
     */
    int getBrokerBidListCount();
    /**
     * <pre>
     *经纪Bid(买)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
     */
    java.util.List<? extends com.futu.openapi.pb.QotCommon.BrokerOrBuilder> 
        getBrokerBidListOrBuilderList();
    /**
     * <pre>
     *经纪Bid(买)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
     */
    com.futu.openapi.pb.QotCommon.BrokerOrBuilder getBrokerBidListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Qot_UpdateBroker.S2C}
   */
  public  static final class S2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateBroker.S2C)
      S2COrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C() {
      brokerAskList_ = java.util.Collections.emptyList();
      brokerBidList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.futu.openapi.pb.QotCommon.Security.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = security_.toBuilder();
              }
              security_ = input.readMessage(com.futu.openapi.pb.QotCommon.Security.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(security_);
                security_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                brokerAskList_ = new java.util.ArrayList<com.futu.openapi.pb.QotCommon.Broker>();
                mutable_bitField0_ |= 0x00000002;
              }
              brokerAskList_.add(
                  input.readMessage(com.futu.openapi.pb.QotCommon.Broker.PARSER, extensionRegistry));
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                brokerBidList_ = new java.util.ArrayList<com.futu.openapi.pb.QotCommon.Broker>();
                mutable_bitField0_ |= 0x00000004;
              }
              brokerBidList_.add(
                  input.readMessage(com.futu.openapi.pb.QotCommon.Broker.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          brokerAskList_ = java.util.Collections.unmodifiableList(brokerAskList_);
        }
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          brokerBidList_ = java.util.Collections.unmodifiableList(brokerBidList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.openapi.pb.QotUpdateBroker.internal_static_Qot_UpdateBroker_S2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.openapi.pb.QotUpdateBroker.internal_static_Qot_UpdateBroker_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.openapi.pb.QotUpdateBroker.S2C.class, com.futu.openapi.pb.QotUpdateBroker.S2C.Builder.class);
    }

    private int bitField0_;
    public static final int SECURITY_FIELD_NUMBER = 1;
    private com.futu.openapi.pb.QotCommon.Security security_;
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public boolean hasSecurity() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public com.futu.openapi.pb.QotCommon.Security getSecurity() {
      return security_ == null ? com.futu.openapi.pb.QotCommon.Security.getDefaultInstance() : security_;
    }
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public com.futu.openapi.pb.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
      return security_ == null ? com.futu.openapi.pb.QotCommon.Security.getDefaultInstance() : security_;
    }

    public static final int BROKERASKLIST_FIELD_NUMBER = 2;
    private java.util.List<com.futu.openapi.pb.QotCommon.Broker> brokerAskList_;
    /**
     * <pre>
     *经纪Ask(卖)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
     */
    public java.util.List<com.futu.openapi.pb.QotCommon.Broker> getBrokerAskListList() {
      return brokerAskList_;
    }
    /**
     * <pre>
     *经纪Ask(卖)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
     */
    public java.util.List<? extends com.futu.openapi.pb.QotCommon.BrokerOrBuilder> 
        getBrokerAskListOrBuilderList() {
      return brokerAskList_;
    }
    /**
     * <pre>
     *经纪Ask(卖)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
     */
    public int getBrokerAskListCount() {
      return brokerAskList_.size();
    }
    /**
     * <pre>
     *经纪Ask(卖)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
     */
    public com.futu.openapi.pb.QotCommon.Broker getBrokerAskList(int index) {
      return brokerAskList_.get(index);
    }
    /**
     * <pre>
     *经纪Ask(卖)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
     */
    public com.futu.openapi.pb.QotCommon.BrokerOrBuilder getBrokerAskListOrBuilder(
        int index) {
      return brokerAskList_.get(index);
    }

    public static final int BROKERBIDLIST_FIELD_NUMBER = 3;
    private java.util.List<com.futu.openapi.pb.QotCommon.Broker> brokerBidList_;
    /**
     * <pre>
     *经纪Bid(买)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
     */
    public java.util.List<com.futu.openapi.pb.QotCommon.Broker> getBrokerBidListList() {
      return brokerBidList_;
    }
    /**
     * <pre>
     *经纪Bid(买)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
     */
    public java.util.List<? extends com.futu.openapi.pb.QotCommon.BrokerOrBuilder> 
        getBrokerBidListOrBuilderList() {
      return brokerBidList_;
    }
    /**
     * <pre>
     *经纪Bid(买)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
     */
    public int getBrokerBidListCount() {
      return brokerBidList_.size();
    }
    /**
     * <pre>
     *经纪Bid(买)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
     */
    public com.futu.openapi.pb.QotCommon.Broker getBrokerBidList(int index) {
      return brokerBidList_.get(index);
    }
    /**
     * <pre>
     *经纪Bid(买)盘
     * </pre>
     *
     * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
     */
    public com.futu.openapi.pb.QotCommon.BrokerOrBuilder getBrokerBidListOrBuilder(
        int index) {
      return brokerBidList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSecurity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSecurity().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getBrokerAskListCount(); i++) {
        if (!getBrokerAskList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getBrokerBidListCount(); i++) {
        if (!getBrokerBidList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getSecurity());
      }
      for (int i = 0; i < brokerAskList_.size(); i++) {
        output.writeMessage(2, brokerAskList_.get(i));
      }
      for (int i = 0; i < brokerBidList_.size(); i++) {
        output.writeMessage(3, brokerBidList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSecurity());
      }
      for (int i = 0; i < brokerAskList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, brokerAskList_.get(i));
      }
      for (int i = 0; i < brokerBidList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, brokerBidList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.futu.openapi.pb.QotUpdateBroker.S2C)) {
        return super.equals(obj);
      }
      com.futu.openapi.pb.QotUpdateBroker.S2C other = (com.futu.openapi.pb.QotUpdateBroker.S2C) obj;

      boolean result = true;
      result = result && (hasSecurity() == other.hasSecurity());
      if (hasSecurity()) {
        result = result && getSecurity()
            .equals(other.getSecurity());
      }
      result = result && getBrokerAskListList()
          .equals(other.getBrokerAskListList());
      result = result && getBrokerBidListList()
          .equals(other.getBrokerBidListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSecurity()) {
        hash = (37 * hash) + SECURITY_FIELD_NUMBER;
        hash = (53 * hash) + getSecurity().hashCode();
      }
      if (getBrokerAskListCount() > 0) {
        hash = (37 * hash) + BROKERASKLIST_FIELD_NUMBER;
        hash = (53 * hash) + getBrokerAskListList().hashCode();
      }
      if (getBrokerBidListCount() > 0) {
        hash = (37 * hash) + BROKERBIDLIST_FIELD_NUMBER;
        hash = (53 * hash) + getBrokerBidListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.futu.openapi.pb.QotUpdateBroker.S2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateBroker.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateBroker.S2C)
        com.futu.openapi.pb.QotUpdateBroker.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.openapi.pb.QotUpdateBroker.internal_static_Qot_UpdateBroker_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.openapi.pb.QotUpdateBroker.internal_static_Qot_UpdateBroker_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.openapi.pb.QotUpdateBroker.S2C.class, com.futu.openapi.pb.QotUpdateBroker.S2C.Builder.class);
      }

      // Construct using com.futu.openapi.pb.QotUpdateBroker.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSecurityFieldBuilder();
          getBrokerAskListFieldBuilder();
          getBrokerBidListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (securityBuilder_ == null) {
          security_ = null;
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (brokerAskListBuilder_ == null) {
          brokerAskList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          brokerAskListBuilder_.clear();
        }
        if (brokerBidListBuilder_ == null) {
          brokerBidList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          brokerBidListBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.openapi.pb.QotUpdateBroker.internal_static_Qot_UpdateBroker_S2C_descriptor;
      }

      public com.futu.openapi.pb.QotUpdateBroker.S2C getDefaultInstanceForType() {
        return com.futu.openapi.pb.QotUpdateBroker.S2C.getDefaultInstance();
      }

      public com.futu.openapi.pb.QotUpdateBroker.S2C build() {
        com.futu.openapi.pb.QotUpdateBroker.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.openapi.pb.QotUpdateBroker.S2C buildPartial() {
        com.futu.openapi.pb.QotUpdateBroker.S2C result = new com.futu.openapi.pb.QotUpdateBroker.S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (securityBuilder_ == null) {
          result.security_ = security_;
        } else {
          result.security_ = securityBuilder_.build();
        }
        if (brokerAskListBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            brokerAskList_ = java.util.Collections.unmodifiableList(brokerAskList_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.brokerAskList_ = brokerAskList_;
        } else {
          result.brokerAskList_ = brokerAskListBuilder_.build();
        }
        if (brokerBidListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            brokerBidList_ = java.util.Collections.unmodifiableList(brokerBidList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.brokerBidList_ = brokerBidList_;
        } else {
          result.brokerBidList_ = brokerBidListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.openapi.pb.QotUpdateBroker.S2C) {
          return mergeFrom((com.futu.openapi.pb.QotUpdateBroker.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.openapi.pb.QotUpdateBroker.S2C other) {
        if (other == com.futu.openapi.pb.QotUpdateBroker.S2C.getDefaultInstance()) return this;
        if (other.hasSecurity()) {
          mergeSecurity(other.getSecurity());
        }
        if (brokerAskListBuilder_ == null) {
          if (!other.brokerAskList_.isEmpty()) {
            if (brokerAskList_.isEmpty()) {
              brokerAskList_ = other.brokerAskList_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBrokerAskListIsMutable();
              brokerAskList_.addAll(other.brokerAskList_);
            }
            onChanged();
          }
        } else {
          if (!other.brokerAskList_.isEmpty()) {
            if (brokerAskListBuilder_.isEmpty()) {
              brokerAskListBuilder_.dispose();
              brokerAskListBuilder_ = null;
              brokerAskList_ = other.brokerAskList_;
              bitField0_ = (bitField0_ & ~0x00000002);
              brokerAskListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBrokerAskListFieldBuilder() : null;
            } else {
              brokerAskListBuilder_.addAllMessages(other.brokerAskList_);
            }
          }
        }
        if (brokerBidListBuilder_ == null) {
          if (!other.brokerBidList_.isEmpty()) {
            if (brokerBidList_.isEmpty()) {
              brokerBidList_ = other.brokerBidList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBrokerBidListIsMutable();
              brokerBidList_.addAll(other.brokerBidList_);
            }
            onChanged();
          }
        } else {
          if (!other.brokerBidList_.isEmpty()) {
            if (brokerBidListBuilder_.isEmpty()) {
              brokerBidListBuilder_.dispose();
              brokerBidListBuilder_ = null;
              brokerBidList_ = other.brokerBidList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              brokerBidListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBrokerBidListFieldBuilder() : null;
            } else {
              brokerBidListBuilder_.addAllMessages(other.brokerBidList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSecurity()) {
          return false;
        }
        if (!getSecurity().isInitialized()) {
          return false;
        }
        for (int i = 0; i < getBrokerAskListCount(); i++) {
          if (!getBrokerAskList(i).isInitialized()) {
            return false;
          }
        }
        for (int i = 0; i < getBrokerBidListCount(); i++) {
          if (!getBrokerBidList(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.openapi.pb.QotUpdateBroker.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.openapi.pb.QotUpdateBroker.S2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.futu.openapi.pb.QotCommon.Security security_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.futu.openapi.pb.QotCommon.Security, com.futu.openapi.pb.QotCommon.Security.Builder, com.futu.openapi.pb.QotCommon.SecurityOrBuilder> securityBuilder_;
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public boolean hasSecurity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public com.futu.openapi.pb.QotCommon.Security getSecurity() {
        if (securityBuilder_ == null) {
          return security_ == null ? com.futu.openapi.pb.QotCommon.Security.getDefaultInstance() : security_;
        } else {
          return securityBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder setSecurity(com.futu.openapi.pb.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          security_ = value;
          onChanged();
        } else {
          securityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder setSecurity(
          com.futu.openapi.pb.QotCommon.Security.Builder builderForValue) {
        if (securityBuilder_ == null) {
          security_ = builderForValue.build();
          onChanged();
        } else {
          securityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder mergeSecurity(com.futu.openapi.pb.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              security_ != null &&
              security_ != com.futu.openapi.pb.QotCommon.Security.getDefaultInstance()) {
            security_ =
              com.futu.openapi.pb.QotCommon.Security.newBuilder(security_).mergeFrom(value).buildPartial();
          } else {
            security_ = value;
          }
          onChanged();
        } else {
          securityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder clearSecurity() {
        if (securityBuilder_ == null) {
          security_ = null;
          onChanged();
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public com.futu.openapi.pb.QotCommon.Security.Builder getSecurityBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSecurityFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public com.futu.openapi.pb.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
        if (securityBuilder_ != null) {
          return securityBuilder_.getMessageOrBuilder();
        } else {
          return security_ == null ?
              com.futu.openapi.pb.QotCommon.Security.getDefaultInstance() : security_;
        }
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.futu.openapi.pb.QotCommon.Security, com.futu.openapi.pb.QotCommon.Security.Builder, com.futu.openapi.pb.QotCommon.SecurityOrBuilder> 
          getSecurityFieldBuilder() {
        if (securityBuilder_ == null) {
          securityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.futu.openapi.pb.QotCommon.Security, com.futu.openapi.pb.QotCommon.Security.Builder, com.futu.openapi.pb.QotCommon.SecurityOrBuilder>(
                  getSecurity(),
                  getParentForChildren(),
                  isClean());
          security_ = null;
        }
        return securityBuilder_;
      }

      private java.util.List<com.futu.openapi.pb.QotCommon.Broker> brokerAskList_ =
        java.util.Collections.emptyList();
      private void ensureBrokerAskListIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          brokerAskList_ = new java.util.ArrayList<com.futu.openapi.pb.QotCommon.Broker>(brokerAskList_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futu.openapi.pb.QotCommon.Broker, com.futu.openapi.pb.QotCommon.Broker.Builder, com.futu.openapi.pb.QotCommon.BrokerOrBuilder> brokerAskListBuilder_;

      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public java.util.List<com.futu.openapi.pb.QotCommon.Broker> getBrokerAskListList() {
        if (brokerAskListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(brokerAskList_);
        } else {
          return brokerAskListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public int getBrokerAskListCount() {
        if (brokerAskListBuilder_ == null) {
          return brokerAskList_.size();
        } else {
          return brokerAskListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public com.futu.openapi.pb.QotCommon.Broker getBrokerAskList(int index) {
        if (brokerAskListBuilder_ == null) {
          return brokerAskList_.get(index);
        } else {
          return brokerAskListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public Builder setBrokerAskList(
          int index, com.futu.openapi.pb.QotCommon.Broker value) {
        if (brokerAskListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokerAskListIsMutable();
          brokerAskList_.set(index, value);
          onChanged();
        } else {
          brokerAskListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public Builder setBrokerAskList(
          int index, com.futu.openapi.pb.QotCommon.Broker.Builder builderForValue) {
        if (brokerAskListBuilder_ == null) {
          ensureBrokerAskListIsMutable();
          brokerAskList_.set(index, builderForValue.build());
          onChanged();
        } else {
          brokerAskListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public Builder addBrokerAskList(com.futu.openapi.pb.QotCommon.Broker value) {
        if (brokerAskListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokerAskListIsMutable();
          brokerAskList_.add(value);
          onChanged();
        } else {
          brokerAskListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public Builder addBrokerAskList(
          int index, com.futu.openapi.pb.QotCommon.Broker value) {
        if (brokerAskListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokerAskListIsMutable();
          brokerAskList_.add(index, value);
          onChanged();
        } else {
          brokerAskListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public Builder addBrokerAskList(
          com.futu.openapi.pb.QotCommon.Broker.Builder builderForValue) {
        if (brokerAskListBuilder_ == null) {
          ensureBrokerAskListIsMutable();
          brokerAskList_.add(builderForValue.build());
          onChanged();
        } else {
          brokerAskListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public Builder addBrokerAskList(
          int index, com.futu.openapi.pb.QotCommon.Broker.Builder builderForValue) {
        if (brokerAskListBuilder_ == null) {
          ensureBrokerAskListIsMutable();
          brokerAskList_.add(index, builderForValue.build());
          onChanged();
        } else {
          brokerAskListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public Builder addAllBrokerAskList(
          java.lang.Iterable<? extends com.futu.openapi.pb.QotCommon.Broker> values) {
        if (brokerAskListBuilder_ == null) {
          ensureBrokerAskListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, brokerAskList_);
          onChanged();
        } else {
          brokerAskListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public Builder clearBrokerAskList() {
        if (brokerAskListBuilder_ == null) {
          brokerAskList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          brokerAskListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public Builder removeBrokerAskList(int index) {
        if (brokerAskListBuilder_ == null) {
          ensureBrokerAskListIsMutable();
          brokerAskList_.remove(index);
          onChanged();
        } else {
          brokerAskListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public com.futu.openapi.pb.QotCommon.Broker.Builder getBrokerAskListBuilder(
          int index) {
        return getBrokerAskListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public com.futu.openapi.pb.QotCommon.BrokerOrBuilder getBrokerAskListOrBuilder(
          int index) {
        if (brokerAskListBuilder_ == null) {
          return brokerAskList_.get(index);  } else {
          return brokerAskListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public java.util.List<? extends com.futu.openapi.pb.QotCommon.BrokerOrBuilder> 
           getBrokerAskListOrBuilderList() {
        if (brokerAskListBuilder_ != null) {
          return brokerAskListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(brokerAskList_);
        }
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public com.futu.openapi.pb.QotCommon.Broker.Builder addBrokerAskListBuilder() {
        return getBrokerAskListFieldBuilder().addBuilder(
            com.futu.openapi.pb.QotCommon.Broker.getDefaultInstance());
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public com.futu.openapi.pb.QotCommon.Broker.Builder addBrokerAskListBuilder(
          int index) {
        return getBrokerAskListFieldBuilder().addBuilder(
            index, com.futu.openapi.pb.QotCommon.Broker.getDefaultInstance());
      }
      /**
       * <pre>
       *经纪Ask(卖)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerAskList = 2;</code>
       */
      public java.util.List<com.futu.openapi.pb.QotCommon.Broker.Builder> 
           getBrokerAskListBuilderList() {
        return getBrokerAskListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futu.openapi.pb.QotCommon.Broker, com.futu.openapi.pb.QotCommon.Broker.Builder, com.futu.openapi.pb.QotCommon.BrokerOrBuilder> 
          getBrokerAskListFieldBuilder() {
        if (brokerAskListBuilder_ == null) {
          brokerAskListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.futu.openapi.pb.QotCommon.Broker, com.futu.openapi.pb.QotCommon.Broker.Builder, com.futu.openapi.pb.QotCommon.BrokerOrBuilder>(
                  brokerAskList_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          brokerAskList_ = null;
        }
        return brokerAskListBuilder_;
      }

      private java.util.List<com.futu.openapi.pb.QotCommon.Broker> brokerBidList_ =
        java.util.Collections.emptyList();
      private void ensureBrokerBidListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          brokerBidList_ = new java.util.ArrayList<com.futu.openapi.pb.QotCommon.Broker>(brokerBidList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futu.openapi.pb.QotCommon.Broker, com.futu.openapi.pb.QotCommon.Broker.Builder, com.futu.openapi.pb.QotCommon.BrokerOrBuilder> brokerBidListBuilder_;

      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public java.util.List<com.futu.openapi.pb.QotCommon.Broker> getBrokerBidListList() {
        if (brokerBidListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(brokerBidList_);
        } else {
          return brokerBidListBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public int getBrokerBidListCount() {
        if (brokerBidListBuilder_ == null) {
          return brokerBidList_.size();
        } else {
          return brokerBidListBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public com.futu.openapi.pb.QotCommon.Broker getBrokerBidList(int index) {
        if (brokerBidListBuilder_ == null) {
          return brokerBidList_.get(index);
        } else {
          return brokerBidListBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public Builder setBrokerBidList(
          int index, com.futu.openapi.pb.QotCommon.Broker value) {
        if (brokerBidListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokerBidListIsMutable();
          brokerBidList_.set(index, value);
          onChanged();
        } else {
          brokerBidListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public Builder setBrokerBidList(
          int index, com.futu.openapi.pb.QotCommon.Broker.Builder builderForValue) {
        if (brokerBidListBuilder_ == null) {
          ensureBrokerBidListIsMutable();
          brokerBidList_.set(index, builderForValue.build());
          onChanged();
        } else {
          brokerBidListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public Builder addBrokerBidList(com.futu.openapi.pb.QotCommon.Broker value) {
        if (brokerBidListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokerBidListIsMutable();
          brokerBidList_.add(value);
          onChanged();
        } else {
          brokerBidListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public Builder addBrokerBidList(
          int index, com.futu.openapi.pb.QotCommon.Broker value) {
        if (brokerBidListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBrokerBidListIsMutable();
          brokerBidList_.add(index, value);
          onChanged();
        } else {
          brokerBidListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public Builder addBrokerBidList(
          com.futu.openapi.pb.QotCommon.Broker.Builder builderForValue) {
        if (brokerBidListBuilder_ == null) {
          ensureBrokerBidListIsMutable();
          brokerBidList_.add(builderForValue.build());
          onChanged();
        } else {
          brokerBidListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public Builder addBrokerBidList(
          int index, com.futu.openapi.pb.QotCommon.Broker.Builder builderForValue) {
        if (brokerBidListBuilder_ == null) {
          ensureBrokerBidListIsMutable();
          brokerBidList_.add(index, builderForValue.build());
          onChanged();
        } else {
          brokerBidListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public Builder addAllBrokerBidList(
          java.lang.Iterable<? extends com.futu.openapi.pb.QotCommon.Broker> values) {
        if (brokerBidListBuilder_ == null) {
          ensureBrokerBidListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, brokerBidList_);
          onChanged();
        } else {
          brokerBidListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public Builder clearBrokerBidList() {
        if (brokerBidListBuilder_ == null) {
          brokerBidList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          brokerBidListBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public Builder removeBrokerBidList(int index) {
        if (brokerBidListBuilder_ == null) {
          ensureBrokerBidListIsMutable();
          brokerBidList_.remove(index);
          onChanged();
        } else {
          brokerBidListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public com.futu.openapi.pb.QotCommon.Broker.Builder getBrokerBidListBuilder(
          int index) {
        return getBrokerBidListFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public com.futu.openapi.pb.QotCommon.BrokerOrBuilder getBrokerBidListOrBuilder(
          int index) {
        if (brokerBidListBuilder_ == null) {
          return brokerBidList_.get(index);  } else {
          return brokerBidListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public java.util.List<? extends com.futu.openapi.pb.QotCommon.BrokerOrBuilder> 
           getBrokerBidListOrBuilderList() {
        if (brokerBidListBuilder_ != null) {
          return brokerBidListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(brokerBidList_);
        }
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public com.futu.openapi.pb.QotCommon.Broker.Builder addBrokerBidListBuilder() {
        return getBrokerBidListFieldBuilder().addBuilder(
            com.futu.openapi.pb.QotCommon.Broker.getDefaultInstance());
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public com.futu.openapi.pb.QotCommon.Broker.Builder addBrokerBidListBuilder(
          int index) {
        return getBrokerBidListFieldBuilder().addBuilder(
            index, com.futu.openapi.pb.QotCommon.Broker.getDefaultInstance());
      }
      /**
       * <pre>
       *经纪Bid(买)盘
       * </pre>
       *
       * <code>repeated .Qot_Common.Broker brokerBidList = 3;</code>
       */
      public java.util.List<com.futu.openapi.pb.QotCommon.Broker.Builder> 
           getBrokerBidListBuilderList() {
        return getBrokerBidListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.futu.openapi.pb.QotCommon.Broker, com.futu.openapi.pb.QotCommon.Broker.Builder, com.futu.openapi.pb.QotCommon.BrokerOrBuilder> 
          getBrokerBidListFieldBuilder() {
        if (brokerBidListBuilder_ == null) {
          brokerBidListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.futu.openapi.pb.QotCommon.Broker, com.futu.openapi.pb.QotCommon.Broker.Builder, com.futu.openapi.pb.QotCommon.BrokerOrBuilder>(
                  brokerBidList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          brokerBidList_ = null;
        }
        return brokerBidListBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Qot_UpdateBroker.S2C)
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateBroker.S2C)
    private static final com.futu.openapi.pb.QotUpdateBroker.S2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.futu.openapi.pb.QotUpdateBroker.S2C();
    }

    public static com.futu.openapi.pb.QotUpdateBroker.S2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C>
        PARSER = new com.google.protobuf.AbstractParser<S2C>() {
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    public com.futu.openapi.pb.QotUpdateBroker.S2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdateBroker.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    boolean hasRetType();
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    int getRetType();

    /**
     * <code>optional string retMsg = 2;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional int32 errCode = 3;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    int getErrCode();

    /**
     * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
     */
    boolean hasS2C();
    /**
     * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
     */
    com.futu.openapi.pb.QotUpdateBroker.S2C getS2C();
    /**
     * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
     */
    com.futu.openapi.pb.QotUpdateBroker.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code Qot_UpdateBroker.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Qot_UpdateBroker.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      retType_ = -400;
      retMsg_ = "";
      errCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              retType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              retMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 34: {
              com.futu.openapi.pb.QotUpdateBroker.S2C.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(com.futu.openapi.pb.QotUpdateBroker.S2C.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.openapi.pb.QotUpdateBroker.internal_static_Qot_UpdateBroker_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.openapi.pb.QotUpdateBroker.internal_static_Qot_UpdateBroker_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.openapi.pb.QotUpdateBroker.Response.class, com.futu.openapi.pb.QotUpdateBroker.Response.Builder.class);
    }

    private int bitField0_;
    public static final int RETTYPE_FIELD_NUMBER = 1;
    private int retType_;
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public boolean hasRetType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public int getRetType() {
      return retType_;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object retMsg_;
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int S2C_FIELD_NUMBER = 4;
    private com.futu.openapi.pb.QotUpdateBroker.S2C s2C_;
    /**
     * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
     */
    public boolean hasS2C() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
     */
    public com.futu.openapi.pb.QotUpdateBroker.S2C getS2C() {
      return s2C_ == null ? com.futu.openapi.pb.QotUpdateBroker.S2C.getDefaultInstance() : s2C_;
    }
    /**
     * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
     */
    public com.futu.openapi.pb.QotUpdateBroker.S2COrBuilder getS2COrBuilder() {
      return s2C_ == null ? com.futu.openapi.pb.QotUpdateBroker.S2C.getDefaultInstance() : s2C_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2C()) {
        if (!getS2C().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getS2C());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getS2C());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.futu.openapi.pb.QotUpdateBroker.Response)) {
        return super.equals(obj);
      }
      com.futu.openapi.pb.QotUpdateBroker.Response other = (com.futu.openapi.pb.QotUpdateBroker.Response) obj;

      boolean result = true;
      result = result && (hasRetType() == other.hasRetType());
      if (hasRetType()) {
        result = result && (getRetType()
            == other.getRetType());
      }
      result = result && (hasRetMsg() == other.hasRetMsg());
      if (hasRetMsg()) {
        result = result && getRetMsg()
            .equals(other.getRetMsg());
      }
      result = result && (hasErrCode() == other.hasErrCode());
      if (hasErrCode()) {
        result = result && (getErrCode()
            == other.getErrCode());
      }
      result = result && (hasS2C() == other.hasS2C());
      if (hasS2C()) {
        result = result && getS2C()
            .equals(other.getS2C());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRetType()) {
        hash = (37 * hash) + RETTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getRetType();
      }
      if (hasRetMsg()) {
        hash = (37 * hash) + RETMSG_FIELD_NUMBER;
        hash = (53 * hash) + getRetMsg().hashCode();
      }
      if (hasErrCode()) {
        hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCode();
      }
      if (hasS2C()) {
        hash = (37 * hash) + S2C_FIELD_NUMBER;
        hash = (53 * hash) + getS2C().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.futu.openapi.pb.QotUpdateBroker.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdateBroker.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.futu.openapi.pb.QotUpdateBroker.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdateBroker.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdateBroker.Response)
        com.futu.openapi.pb.QotUpdateBroker.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.openapi.pb.QotUpdateBroker.internal_static_Qot_UpdateBroker_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.openapi.pb.QotUpdateBroker.internal_static_Qot_UpdateBroker_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.openapi.pb.QotUpdateBroker.Response.class, com.futu.openapi.pb.QotUpdateBroker.Response.Builder.class);
      }

      // Construct using com.futu.openapi.pb.QotUpdateBroker.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getS2CFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        retType_ = -400;
        bitField0_ = (bitField0_ & ~0x00000001);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CBuilder_ == null) {
          s2C_ = null;
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.openapi.pb.QotUpdateBroker.internal_static_Qot_UpdateBroker_Response_descriptor;
      }

      public com.futu.openapi.pb.QotUpdateBroker.Response getDefaultInstanceForType() {
        return com.futu.openapi.pb.QotUpdateBroker.Response.getDefaultInstance();
      }

      public com.futu.openapi.pb.QotUpdateBroker.Response build() {
        com.futu.openapi.pb.QotUpdateBroker.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.openapi.pb.QotUpdateBroker.Response buildPartial() {
        com.futu.openapi.pb.QotUpdateBroker.Response result = new com.futu.openapi.pb.QotUpdateBroker.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retType_ = retType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (s2CBuilder_ == null) {
          result.s2C_ = s2C_;
        } else {
          result.s2C_ = s2CBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.openapi.pb.QotUpdateBroker.Response) {
          return mergeFrom((com.futu.openapi.pb.QotUpdateBroker.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.openapi.pb.QotUpdateBroker.Response other) {
        if (other == com.futu.openapi.pb.QotUpdateBroker.Response.getDefaultInstance()) return this;
        if (other.hasRetType()) {
          setRetType(other.getRetType());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000002;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRetType()) {
          return false;
        }
        if (hasS2C()) {
          if (!getS2C().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.openapi.pb.QotUpdateBroker.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.openapi.pb.QotUpdateBroker.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retType_ = -400;
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public boolean hasRetType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public int getRetType() {
        return retType_;
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder setRetType(int value) {
        bitField0_ |= 0x00000001;
        retType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder clearRetType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retType_ = -400;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private com.futu.openapi.pb.QotUpdateBroker.S2C s2C_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.futu.openapi.pb.QotUpdateBroker.S2C, com.futu.openapi.pb.QotUpdateBroker.S2C.Builder, com.futu.openapi.pb.QotUpdateBroker.S2COrBuilder> s2CBuilder_;
      /**
       * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
       */
      public boolean hasS2C() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
       */
      public com.futu.openapi.pb.QotUpdateBroker.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_ == null ? com.futu.openapi.pb.QotUpdateBroker.S2C.getDefaultInstance() : s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
       */
      public Builder setS2C(com.futu.openapi.pb.QotUpdateBroker.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
       */
      public Builder setS2C(
          com.futu.openapi.pb.QotUpdateBroker.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
       */
      public Builder mergeS2C(com.futu.openapi.pb.QotUpdateBroker.S2C value) {
        if (s2CBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              s2C_ != null &&
              s2C_ != com.futu.openapi.pb.QotUpdateBroker.S2C.getDefaultInstance()) {
            s2C_ =
              com.futu.openapi.pb.QotUpdateBroker.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = null;
          onChanged();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
       */
      public com.futu.openapi.pb.QotUpdateBroker.S2C.Builder getS2CBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
       */
      public com.futu.openapi.pb.QotUpdateBroker.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_ == null ?
              com.futu.openapi.pb.QotUpdateBroker.S2C.getDefaultInstance() : s2C_;
        }
      }
      /**
       * <code>optional .Qot_UpdateBroker.S2C s2c = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.futu.openapi.pb.QotUpdateBroker.S2C, com.futu.openapi.pb.QotUpdateBroker.S2C.Builder, com.futu.openapi.pb.QotUpdateBroker.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.futu.openapi.pb.QotUpdateBroker.S2C, com.futu.openapi.pb.QotUpdateBroker.S2C.Builder, com.futu.openapi.pb.QotUpdateBroker.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Qot_UpdateBroker.Response)
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdateBroker.Response)
    private static final com.futu.openapi.pb.QotUpdateBroker.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.futu.openapi.pb.QotUpdateBroker.Response();
    }

    public static com.futu.openapi.pb.QotUpdateBroker.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.futu.openapi.pb.QotUpdateBroker.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateBroker_S2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Qot_UpdateBroker_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdateBroker_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Qot_UpdateBroker_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026Qot_UpdateBroker.proto\022\020Qot_UpdateBrok" +
      "er\032\014Common.proto\032\020Qot_Common.proto\"\203\001\n\003S" +
      "2C\022&\n\010security\030\001 \002(\0132\024.Qot_Common.Securi" +
      "ty\022)\n\rbrokerAskList\030\002 \003(\0132\022.Qot_Common.B" +
      "roker\022)\n\rbrokerBidList\030\003 \003(\0132\022.Qot_Commo" +
      "n.Broker\"f\n\010Response\022\025\n\007retType\030\001 \002(\005:\004-" +
      "400\022\016\n\006retMsg\030\002 \001(\t\022\017\n\007errCode\030\003 \001(\005\022\"\n\003" +
      "s2c\030\004 \001(\0132\025.Qot_UpdateBroker.S2CBF\n\023com." +
      "futu.openapi.pbZ/github.com/futuopen/fta" +
      "pi4go/pb/qotupdatebroker"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.futu.openapi.pb.Common.getDescriptor(),
          com.futu.openapi.pb.QotCommon.getDescriptor(),
        }, assigner);
    internal_static_Qot_UpdateBroker_S2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Qot_UpdateBroker_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Qot_UpdateBroker_S2C_descriptor,
        new java.lang.String[] { "Security", "BrokerAskList", "BrokerBidList", });
    internal_static_Qot_UpdateBroker_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Qot_UpdateBroker_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Qot_UpdateBroker_Response_descriptor,
        new java.lang.String[] { "RetType", "RetMsg", "ErrCode", "S2C", });
    com.futu.openapi.pb.Common.getDescriptor();
    com.futu.openapi.pb.QotCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
