// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Qot_UpdatePriceReminder.proto

package com.futu.openapi.pb;

public final class QotUpdatePriceReminder {
  private QotUpdatePriceReminder() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code Qot_UpdatePriceReminder.MarketStatus}
   */
  public enum MarketStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>MarketStatus_Unknow = 0;</code>
     */
    MarketStatus_Unknow(0),
    /**
     * <pre>
     * 盘中
     * </pre>
     *
     * <code>MarketStatus_Open = 1;</code>
     */
    MarketStatus_Open(1),
    /**
     * <pre>
     * 美股盘前
     * </pre>
     *
     * <code>MarketStatus_USPre = 2;</code>
     */
    MarketStatus_USPre(2),
    /**
     * <pre>
     * 美股盘后
     * </pre>
     *
     * <code>MarketStatus_USAfter = 3;</code>
     */
    MarketStatus_USAfter(3),
    ;

    /**
     * <code>MarketStatus_Unknow = 0;</code>
     */
    public static final int MarketStatus_Unknow_VALUE = 0;
    /**
     * <pre>
     * 盘中
     * </pre>
     *
     * <code>MarketStatus_Open = 1;</code>
     */
    public static final int MarketStatus_Open_VALUE = 1;
    /**
     * <pre>
     * 美股盘前
     * </pre>
     *
     * <code>MarketStatus_USPre = 2;</code>
     */
    public static final int MarketStatus_USPre_VALUE = 2;
    /**
     * <pre>
     * 美股盘后
     * </pre>
     *
     * <code>MarketStatus_USAfter = 3;</code>
     */
    public static final int MarketStatus_USAfter_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MarketStatus valueOf(int value) {
      return forNumber(value);
    }

    public static MarketStatus forNumber(int value) {
      switch (value) {
        case 0: return MarketStatus_Unknow;
        case 1: return MarketStatus_Open;
        case 2: return MarketStatus_USPre;
        case 3: return MarketStatus_USAfter;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MarketStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MarketStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MarketStatus>() {
            public MarketStatus findValueByNumber(int number) {
              return MarketStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.futu.openapi.pb.QotUpdatePriceReminder.getDescriptor().getEnumTypes().get(0);
    }

    private static final MarketStatus[] VALUES = values();

    public static MarketStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MarketStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Qot_UpdatePriceReminder.MarketStatus)
  }

  public interface S2COrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdatePriceReminder.S2C)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    boolean hasSecurity();
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    com.futu.openapi.pb.QotCommon.Security getSecurity();
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    com.futu.openapi.pb.QotCommon.SecurityOrBuilder getSecurityOrBuilder();

    /**
     * <pre>
     *价格
     * </pre>
     *
     * <code>required double price = 2;</code>
     */
    boolean hasPrice();
    /**
     * <pre>
     *价格
     * </pre>
     *
     * <code>required double price = 2;</code>
     */
    double getPrice();

    /**
     * <pre>
     *涨跌幅
     * </pre>
     *
     * <code>required double changeRate = 3;</code>
     */
    boolean hasChangeRate();
    /**
     * <pre>
     *涨跌幅
     * </pre>
     *
     * <code>required double changeRate = 3;</code>
     */
    double getChangeRate();

    /**
     * <pre>
     *市场状态
     * </pre>
     *
     * <code>required int32 marketStatus = 4;</code>
     */
    boolean hasMarketStatus();
    /**
     * <pre>
     *市场状态
     * </pre>
     *
     * <code>required int32 marketStatus = 4;</code>
     */
    int getMarketStatus();

    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>required string content = 5;</code>
     */
    boolean hasContent();
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>required string content = 5;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>required string content = 5;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *备注仅支持 20 个以内的中文字符
     * </pre>
     *
     * <code>required string note = 6;</code>
     */
    boolean hasNote();
    /**
     * <pre>
     *备注仅支持 20 个以内的中文字符
     * </pre>
     *
     * <code>required string note = 6;</code>
     */
    java.lang.String getNote();
    /**
     * <pre>
     *备注仅支持 20 个以内的中文字符
     * </pre>
     *
     * <code>required string note = 6;</code>
     */
    com.google.protobuf.ByteString
        getNoteBytes();

    /**
     * <pre>
     * 到价提醒的标识
     * </pre>
     *
     * <code>optional int64 key = 7;</code>
     */
    boolean hasKey();
    /**
     * <pre>
     * 到价提醒的标识
     * </pre>
     *
     * <code>optional int64 key = 7;</code>
     */
    long getKey();

    /**
     * <pre>
     * Qot_Common::PriceReminderType，提醒类型
     * </pre>
     *
     * <code>optional int32 type = 8;</code>
     */
    boolean hasType();
    /**
     * <pre>
     * Qot_Common::PriceReminderType，提醒类型
     * </pre>
     *
     * <code>optional int32 type = 8;</code>
     */
    int getType();

    /**
     * <pre>
     * 设置的提醒值
     * </pre>
     *
     * <code>optional double setValue = 9;</code>
     */
    boolean hasSetValue();
    /**
     * <pre>
     * 设置的提醒值
     * </pre>
     *
     * <code>optional double setValue = 9;</code>
     */
    double getSetValue();

    /**
     * <pre>
     * 设置的提醒类型触发时当前值
     * </pre>
     *
     * <code>optional double curValue = 10;</code>
     */
    boolean hasCurValue();
    /**
     * <pre>
     * 设置的提醒类型触发时当前值
     * </pre>
     *
     * <code>optional double curValue = 10;</code>
     */
    double getCurValue();
  }
  /**
   * Protobuf type {@code Qot_UpdatePriceReminder.S2C}
   */
  public  static final class S2C extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Qot_UpdatePriceReminder.S2C)
      S2COrBuilder {
  private static final long serialVersionUID = 0L;
    // Use S2C.newBuilder() to construct.
    private S2C(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private S2C() {
      price_ = 0D;
      changeRate_ = 0D;
      marketStatus_ = 0;
      content_ = "";
      note_ = "";
      key_ = 0L;
      type_ = 0;
      setValue_ = 0D;
      curValue_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private S2C(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.futu.openapi.pb.QotCommon.Security.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = security_.toBuilder();
              }
              security_ = input.readMessage(com.futu.openapi.pb.QotCommon.Security.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(security_);
                security_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              price_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              changeRate_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              marketStatus_ = input.readInt32();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              content_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              note_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              key_ = input.readInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              type_ = input.readInt32();
              break;
            }
            case 73: {
              bitField0_ |= 0x00000100;
              setValue_ = input.readDouble();
              break;
            }
            case 81: {
              bitField0_ |= 0x00000200;
              curValue_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.openapi.pb.QotUpdatePriceReminder.internal_static_Qot_UpdatePriceReminder_S2C_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.openapi.pb.QotUpdatePriceReminder.internal_static_Qot_UpdatePriceReminder_S2C_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.openapi.pb.QotUpdatePriceReminder.S2C.class, com.futu.openapi.pb.QotUpdatePriceReminder.S2C.Builder.class);
    }

    private int bitField0_;
    public static final int SECURITY_FIELD_NUMBER = 1;
    private com.futu.openapi.pb.QotCommon.Security security_;
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public boolean hasSecurity() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public com.futu.openapi.pb.QotCommon.Security getSecurity() {
      return security_ == null ? com.futu.openapi.pb.QotCommon.Security.getDefaultInstance() : security_;
    }
    /**
     * <pre>
     *股票
     * </pre>
     *
     * <code>required .Qot_Common.Security security = 1;</code>
     */
    public com.futu.openapi.pb.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
      return security_ == null ? com.futu.openapi.pb.QotCommon.Security.getDefaultInstance() : security_;
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private double price_;
    /**
     * <pre>
     *价格
     * </pre>
     *
     * <code>required double price = 2;</code>
     */
    public boolean hasPrice() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     *价格
     * </pre>
     *
     * <code>required double price = 2;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int CHANGERATE_FIELD_NUMBER = 3;
    private double changeRate_;
    /**
     * <pre>
     *涨跌幅
     * </pre>
     *
     * <code>required double changeRate = 3;</code>
     */
    public boolean hasChangeRate() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     *涨跌幅
     * </pre>
     *
     * <code>required double changeRate = 3;</code>
     */
    public double getChangeRate() {
      return changeRate_;
    }

    public static final int MARKETSTATUS_FIELD_NUMBER = 4;
    private int marketStatus_;
    /**
     * <pre>
     *市场状态
     * </pre>
     *
     * <code>required int32 marketStatus = 4;</code>
     */
    public boolean hasMarketStatus() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *市场状态
     * </pre>
     *
     * <code>required int32 marketStatus = 4;</code>
     */
    public int getMarketStatus() {
      return marketStatus_;
    }

    public static final int CONTENT_FIELD_NUMBER = 5;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>required string content = 5;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>required string content = 5;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *内容
     * </pre>
     *
     * <code>required string content = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NOTE_FIELD_NUMBER = 6;
    private volatile java.lang.Object note_;
    /**
     * <pre>
     *备注仅支持 20 个以内的中文字符
     * </pre>
     *
     * <code>required string note = 6;</code>
     */
    public boolean hasNote() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <pre>
     *备注仅支持 20 个以内的中文字符
     * </pre>
     *
     * <code>required string note = 6;</code>
     */
    public java.lang.String getNote() {
      java.lang.Object ref = note_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          note_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     *备注仅支持 20 个以内的中文字符
     * </pre>
     *
     * <code>required string note = 6;</code>
     */
    public com.google.protobuf.ByteString
        getNoteBytes() {
      java.lang.Object ref = note_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        note_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 7;
    private long key_;
    /**
     * <pre>
     * 到价提醒的标识
     * </pre>
     *
     * <code>optional int64 key = 7;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <pre>
     * 到价提醒的标识
     * </pre>
     *
     * <code>optional int64 key = 7;</code>
     */
    public long getKey() {
      return key_;
    }

    public static final int TYPE_FIELD_NUMBER = 8;
    private int type_;
    /**
     * <pre>
     * Qot_Common::PriceReminderType，提醒类型
     * </pre>
     *
     * <code>optional int32 type = 8;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * Qot_Common::PriceReminderType，提醒类型
     * </pre>
     *
     * <code>optional int32 type = 8;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int SETVALUE_FIELD_NUMBER = 9;
    private double setValue_;
    /**
     * <pre>
     * 设置的提醒值
     * </pre>
     *
     * <code>optional double setValue = 9;</code>
     */
    public boolean hasSetValue() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <pre>
     * 设置的提醒值
     * </pre>
     *
     * <code>optional double setValue = 9;</code>
     */
    public double getSetValue() {
      return setValue_;
    }

    public static final int CURVALUE_FIELD_NUMBER = 10;
    private double curValue_;
    /**
     * <pre>
     * 设置的提醒类型触发时当前值
     * </pre>
     *
     * <code>optional double curValue = 10;</code>
     */
    public boolean hasCurValue() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <pre>
     * 设置的提醒类型触发时当前值
     * </pre>
     *
     * <code>optional double curValue = 10;</code>
     */
    public double getCurValue() {
      return curValue_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSecurity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasChangeRate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMarketStatus()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNote()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSecurity().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getSecurity());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, price_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, changeRate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, marketStatus_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, note_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt64(7, key_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, type_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeDouble(9, setValue_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeDouble(10, curValue_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSecurity());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, price_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, changeRate_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, marketStatus_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, note_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, key_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, type_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, setValue_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, curValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.futu.openapi.pb.QotUpdatePriceReminder.S2C)) {
        return super.equals(obj);
      }
      com.futu.openapi.pb.QotUpdatePriceReminder.S2C other = (com.futu.openapi.pb.QotUpdatePriceReminder.S2C) obj;

      boolean result = true;
      result = result && (hasSecurity() == other.hasSecurity());
      if (hasSecurity()) {
        result = result && getSecurity()
            .equals(other.getSecurity());
      }
      result = result && (hasPrice() == other.hasPrice());
      if (hasPrice()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getPrice())
            == java.lang.Double.doubleToLongBits(
                other.getPrice()));
      }
      result = result && (hasChangeRate() == other.hasChangeRate());
      if (hasChangeRate()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getChangeRate())
            == java.lang.Double.doubleToLongBits(
                other.getChangeRate()));
      }
      result = result && (hasMarketStatus() == other.hasMarketStatus());
      if (hasMarketStatus()) {
        result = result && (getMarketStatus()
            == other.getMarketStatus());
      }
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && (hasNote() == other.hasNote());
      if (hasNote()) {
        result = result && getNote()
            .equals(other.getNote());
      }
      result = result && (hasKey() == other.hasKey());
      if (hasKey()) {
        result = result && (getKey()
            == other.getKey());
      }
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && (getType()
            == other.getType());
      }
      result = result && (hasSetValue() == other.hasSetValue());
      if (hasSetValue()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getSetValue())
            == java.lang.Double.doubleToLongBits(
                other.getSetValue()));
      }
      result = result && (hasCurValue() == other.hasCurValue());
      if (hasCurValue()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getCurValue())
            == java.lang.Double.doubleToLongBits(
                other.getCurValue()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSecurity()) {
        hash = (37 * hash) + SECURITY_FIELD_NUMBER;
        hash = (53 * hash) + getSecurity().hashCode();
      }
      if (hasPrice()) {
        hash = (37 * hash) + PRICE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getPrice()));
      }
      if (hasChangeRate()) {
        hash = (37 * hash) + CHANGERATE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getChangeRate()));
      }
      if (hasMarketStatus()) {
        hash = (37 * hash) + MARKETSTATUS_FIELD_NUMBER;
        hash = (53 * hash) + getMarketStatus();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      if (hasNote()) {
        hash = (37 * hash) + NOTE_FIELD_NUMBER;
        hash = (53 * hash) + getNote().hashCode();
      }
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getKey());
      }
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType();
      }
      if (hasSetValue()) {
        hash = (37 * hash) + SETVALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getSetValue()));
      }
      if (hasCurValue()) {
        hash = (37 * hash) + CURVALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getCurValue()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.futu.openapi.pb.QotUpdatePriceReminder.S2C prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdatePriceReminder.S2C}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdatePriceReminder.S2C)
        com.futu.openapi.pb.QotUpdatePriceReminder.S2COrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.openapi.pb.QotUpdatePriceReminder.internal_static_Qot_UpdatePriceReminder_S2C_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.openapi.pb.QotUpdatePriceReminder.internal_static_Qot_UpdatePriceReminder_S2C_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.openapi.pb.QotUpdatePriceReminder.S2C.class, com.futu.openapi.pb.QotUpdatePriceReminder.S2C.Builder.class);
      }

      // Construct using com.futu.openapi.pb.QotUpdatePriceReminder.S2C.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSecurityFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (securityBuilder_ == null) {
          security_ = null;
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        price_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        changeRate_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        marketStatus_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        note_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        key_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        setValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000100);
        curValue_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.openapi.pb.QotUpdatePriceReminder.internal_static_Qot_UpdatePriceReminder_S2C_descriptor;
      }

      public com.futu.openapi.pb.QotUpdatePriceReminder.S2C getDefaultInstanceForType() {
        return com.futu.openapi.pb.QotUpdatePriceReminder.S2C.getDefaultInstance();
      }

      public com.futu.openapi.pb.QotUpdatePriceReminder.S2C build() {
        com.futu.openapi.pb.QotUpdatePriceReminder.S2C result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.openapi.pb.QotUpdatePriceReminder.S2C buildPartial() {
        com.futu.openapi.pb.QotUpdatePriceReminder.S2C result = new com.futu.openapi.pb.QotUpdatePriceReminder.S2C(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (securityBuilder_ == null) {
          result.security_ = security_;
        } else {
          result.security_ = securityBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.price_ = price_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.changeRate_ = changeRate_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.marketStatus_ = marketStatus_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.content_ = content_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.note_ = note_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.setValue_ = setValue_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.curValue_ = curValue_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.openapi.pb.QotUpdatePriceReminder.S2C) {
          return mergeFrom((com.futu.openapi.pb.QotUpdatePriceReminder.S2C)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.openapi.pb.QotUpdatePriceReminder.S2C other) {
        if (other == com.futu.openapi.pb.QotUpdatePriceReminder.S2C.getDefaultInstance()) return this;
        if (other.hasSecurity()) {
          mergeSecurity(other.getSecurity());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasChangeRate()) {
          setChangeRate(other.getChangeRate());
        }
        if (other.hasMarketStatus()) {
          setMarketStatus(other.getMarketStatus());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000010;
          content_ = other.content_;
          onChanged();
        }
        if (other.hasNote()) {
          bitField0_ |= 0x00000020;
          note_ = other.note_;
          onChanged();
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasSetValue()) {
          setSetValue(other.getSetValue());
        }
        if (other.hasCurValue()) {
          setCurValue(other.getCurValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSecurity()) {
          return false;
        }
        if (!hasPrice()) {
          return false;
        }
        if (!hasChangeRate()) {
          return false;
        }
        if (!hasMarketStatus()) {
          return false;
        }
        if (!hasContent()) {
          return false;
        }
        if (!hasNote()) {
          return false;
        }
        if (!getSecurity().isInitialized()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.openapi.pb.QotUpdatePriceReminder.S2C parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.openapi.pb.QotUpdatePriceReminder.S2C) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.futu.openapi.pb.QotCommon.Security security_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.futu.openapi.pb.QotCommon.Security, com.futu.openapi.pb.QotCommon.Security.Builder, com.futu.openapi.pb.QotCommon.SecurityOrBuilder> securityBuilder_;
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public boolean hasSecurity() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public com.futu.openapi.pb.QotCommon.Security getSecurity() {
        if (securityBuilder_ == null) {
          return security_ == null ? com.futu.openapi.pb.QotCommon.Security.getDefaultInstance() : security_;
        } else {
          return securityBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder setSecurity(com.futu.openapi.pb.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          security_ = value;
          onChanged();
        } else {
          securityBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder setSecurity(
          com.futu.openapi.pb.QotCommon.Security.Builder builderForValue) {
        if (securityBuilder_ == null) {
          security_ = builderForValue.build();
          onChanged();
        } else {
          securityBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder mergeSecurity(com.futu.openapi.pb.QotCommon.Security value) {
        if (securityBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              security_ != null &&
              security_ != com.futu.openapi.pb.QotCommon.Security.getDefaultInstance()) {
            security_ =
              com.futu.openapi.pb.QotCommon.Security.newBuilder(security_).mergeFrom(value).buildPartial();
          } else {
            security_ = value;
          }
          onChanged();
        } else {
          securityBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public Builder clearSecurity() {
        if (securityBuilder_ == null) {
          security_ = null;
          onChanged();
        } else {
          securityBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public com.futu.openapi.pb.QotCommon.Security.Builder getSecurityBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSecurityFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      public com.futu.openapi.pb.QotCommon.SecurityOrBuilder getSecurityOrBuilder() {
        if (securityBuilder_ != null) {
          return securityBuilder_.getMessageOrBuilder();
        } else {
          return security_ == null ?
              com.futu.openapi.pb.QotCommon.Security.getDefaultInstance() : security_;
        }
      }
      /**
       * <pre>
       *股票
       * </pre>
       *
       * <code>required .Qot_Common.Security security = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.futu.openapi.pb.QotCommon.Security, com.futu.openapi.pb.QotCommon.Security.Builder, com.futu.openapi.pb.QotCommon.SecurityOrBuilder> 
          getSecurityFieldBuilder() {
        if (securityBuilder_ == null) {
          securityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.futu.openapi.pb.QotCommon.Security, com.futu.openapi.pb.QotCommon.Security.Builder, com.futu.openapi.pb.QotCommon.SecurityOrBuilder>(
                  getSecurity(),
                  getParentForChildren(),
                  isClean());
          security_ = null;
        }
        return securityBuilder_;
      }

      private double price_ ;
      /**
       * <pre>
       *价格
       * </pre>
       *
       * <code>required double price = 2;</code>
       */
      public boolean hasPrice() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       *价格
       * </pre>
       *
       * <code>required double price = 2;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <pre>
       *价格
       * </pre>
       *
       * <code>required double price = 2;</code>
       */
      public Builder setPrice(double value) {
        bitField0_ |= 0x00000002;
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *价格
       * </pre>
       *
       * <code>required double price = 2;</code>
       */
      public Builder clearPrice() {
        bitField0_ = (bitField0_ & ~0x00000002);
        price_ = 0D;
        onChanged();
        return this;
      }

      private double changeRate_ ;
      /**
       * <pre>
       *涨跌幅
       * </pre>
       *
       * <code>required double changeRate = 3;</code>
       */
      public boolean hasChangeRate() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       *涨跌幅
       * </pre>
       *
       * <code>required double changeRate = 3;</code>
       */
      public double getChangeRate() {
        return changeRate_;
      }
      /**
       * <pre>
       *涨跌幅
       * </pre>
       *
       * <code>required double changeRate = 3;</code>
       */
      public Builder setChangeRate(double value) {
        bitField0_ |= 0x00000004;
        changeRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *涨跌幅
       * </pre>
       *
       * <code>required double changeRate = 3;</code>
       */
      public Builder clearChangeRate() {
        bitField0_ = (bitField0_ & ~0x00000004);
        changeRate_ = 0D;
        onChanged();
        return this;
      }

      private int marketStatus_ ;
      /**
       * <pre>
       *市场状态
       * </pre>
       *
       * <code>required int32 marketStatus = 4;</code>
       */
      public boolean hasMarketStatus() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <pre>
       *市场状态
       * </pre>
       *
       * <code>required int32 marketStatus = 4;</code>
       */
      public int getMarketStatus() {
        return marketStatus_;
      }
      /**
       * <pre>
       *市场状态
       * </pre>
       *
       * <code>required int32 marketStatus = 4;</code>
       */
      public Builder setMarketStatus(int value) {
        bitField0_ |= 0x00000008;
        marketStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *市场状态
       * </pre>
       *
       * <code>required int32 marketStatus = 4;</code>
       */
      public Builder clearMarketStatus() {
        bitField0_ = (bitField0_ & ~0x00000008);
        marketStatus_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>required string content = 5;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>required string content = 5;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>required string content = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>required string content = 5;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>required string content = 5;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *内容
       * </pre>
       *
       * <code>required string content = 5;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object note_ = "";
      /**
       * <pre>
       *备注仅支持 20 个以内的中文字符
       * </pre>
       *
       * <code>required string note = 6;</code>
       */
      public boolean hasNote() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <pre>
       *备注仅支持 20 个以内的中文字符
       * </pre>
       *
       * <code>required string note = 6;</code>
       */
      public java.lang.String getNote() {
        java.lang.Object ref = note_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            note_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *备注仅支持 20 个以内的中文字符
       * </pre>
       *
       * <code>required string note = 6;</code>
       */
      public com.google.protobuf.ByteString
          getNoteBytes() {
        java.lang.Object ref = note_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          note_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *备注仅支持 20 个以内的中文字符
       * </pre>
       *
       * <code>required string note = 6;</code>
       */
      public Builder setNote(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        note_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *备注仅支持 20 个以内的中文字符
       * </pre>
       *
       * <code>required string note = 6;</code>
       */
      public Builder clearNote() {
        bitField0_ = (bitField0_ & ~0x00000020);
        note_ = getDefaultInstance().getNote();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *备注仅支持 20 个以内的中文字符
       * </pre>
       *
       * <code>required string note = 6;</code>
       */
      public Builder setNoteBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        note_ = value;
        onChanged();
        return this;
      }

      private long key_ ;
      /**
       * <pre>
       * 到价提醒的标识
       * </pre>
       *
       * <code>optional int64 key = 7;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <pre>
       * 到价提醒的标识
       * </pre>
       *
       * <code>optional int64 key = 7;</code>
       */
      public long getKey() {
        return key_;
      }
      /**
       * <pre>
       * 到价提醒的标识
       * </pre>
       *
       * <code>optional int64 key = 7;</code>
       */
      public Builder setKey(long value) {
        bitField0_ |= 0x00000040;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 到价提醒的标识
       * </pre>
       *
       * <code>optional int64 key = 7;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000040);
        key_ = 0L;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       * Qot_Common::PriceReminderType，提醒类型
       * </pre>
       *
       * <code>optional int32 type = 8;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <pre>
       * Qot_Common::PriceReminderType，提醒类型
       * </pre>
       *
       * <code>optional int32 type = 8;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       * Qot_Common::PriceReminderType，提醒类型
       * </pre>
       *
       * <code>optional int32 type = 8;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000080;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Qot_Common::PriceReminderType，提醒类型
       * </pre>
       *
       * <code>optional int32 type = 8;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000080);
        type_ = 0;
        onChanged();
        return this;
      }

      private double setValue_ ;
      /**
       * <pre>
       * 设置的提醒值
       * </pre>
       *
       * <code>optional double setValue = 9;</code>
       */
      public boolean hasSetValue() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <pre>
       * 设置的提醒值
       * </pre>
       *
       * <code>optional double setValue = 9;</code>
       */
      public double getSetValue() {
        return setValue_;
      }
      /**
       * <pre>
       * 设置的提醒值
       * </pre>
       *
       * <code>optional double setValue = 9;</code>
       */
      public Builder setSetValue(double value) {
        bitField0_ |= 0x00000100;
        setValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设置的提醒值
       * </pre>
       *
       * <code>optional double setValue = 9;</code>
       */
      public Builder clearSetValue() {
        bitField0_ = (bitField0_ & ~0x00000100);
        setValue_ = 0D;
        onChanged();
        return this;
      }

      private double curValue_ ;
      /**
       * <pre>
       * 设置的提醒类型触发时当前值
       * </pre>
       *
       * <code>optional double curValue = 10;</code>
       */
      public boolean hasCurValue() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <pre>
       * 设置的提醒类型触发时当前值
       * </pre>
       *
       * <code>optional double curValue = 10;</code>
       */
      public double getCurValue() {
        return curValue_;
      }
      /**
       * <pre>
       * 设置的提醒类型触发时当前值
       * </pre>
       *
       * <code>optional double curValue = 10;</code>
       */
      public Builder setCurValue(double value) {
        bitField0_ |= 0x00000200;
        curValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 设置的提醒类型触发时当前值
       * </pre>
       *
       * <code>optional double curValue = 10;</code>
       */
      public Builder clearCurValue() {
        bitField0_ = (bitField0_ & ~0x00000200);
        curValue_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Qot_UpdatePriceReminder.S2C)
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdatePriceReminder.S2C)
    private static final com.futu.openapi.pb.QotUpdatePriceReminder.S2C DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.futu.openapi.pb.QotUpdatePriceReminder.S2C();
    }

    public static com.futu.openapi.pb.QotUpdatePriceReminder.S2C getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<S2C>
        PARSER = new com.google.protobuf.AbstractParser<S2C>() {
      public S2C parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new S2C(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<S2C> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<S2C> getParserForType() {
      return PARSER;
    }

    public com.futu.openapi.pb.QotUpdatePriceReminder.S2C getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Qot_UpdatePriceReminder.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    boolean hasRetType();
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    int getRetType();

    /**
     * <code>optional string retMsg = 2;</code>
     */
    boolean hasRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    java.lang.String getRetMsg();
    /**
     * <code>optional string retMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getRetMsgBytes();

    /**
     * <code>optional int32 errCode = 3;</code>
     */
    boolean hasErrCode();
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    int getErrCode();

    /**
     * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
     */
    boolean hasS2C();
    /**
     * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
     */
    com.futu.openapi.pb.QotUpdatePriceReminder.S2C getS2C();
    /**
     * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
     */
    com.futu.openapi.pb.QotUpdatePriceReminder.S2COrBuilder getS2COrBuilder();
  }
  /**
   * Protobuf type {@code Qot_UpdatePriceReminder.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Qot_UpdatePriceReminder.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      retType_ = -400;
      retMsg_ = "";
      errCode_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              retType_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              retMsg_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              errCode_ = input.readInt32();
              break;
            }
            case 34: {
              com.futu.openapi.pb.QotUpdatePriceReminder.S2C.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = s2C_.toBuilder();
              }
              s2C_ = input.readMessage(com.futu.openapi.pb.QotUpdatePriceReminder.S2C.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(s2C_);
                s2C_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.futu.openapi.pb.QotUpdatePriceReminder.internal_static_Qot_UpdatePriceReminder_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.futu.openapi.pb.QotUpdatePriceReminder.internal_static_Qot_UpdatePriceReminder_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.futu.openapi.pb.QotUpdatePriceReminder.Response.class, com.futu.openapi.pb.QotUpdatePriceReminder.Response.Builder.class);
    }

    private int bitField0_;
    public static final int RETTYPE_FIELD_NUMBER = 1;
    private int retType_;
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public boolean hasRetType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     *RetType,返回结果
     * </pre>
     *
     * <code>required int32 retType = 1 [default = -400];</code>
     */
    public int getRetType() {
      return retType_;
    }

    public static final int RETMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object retMsg_;
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public boolean hasRetMsg() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public java.lang.String getRetMsg() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          retMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string retMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRetMsgBytes() {
      java.lang.Object ref = retMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        retMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERRCODE_FIELD_NUMBER = 3;
    private int errCode_;
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public boolean hasErrCode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 errCode = 3;</code>
     */
    public int getErrCode() {
      return errCode_;
    }

    public static final int S2C_FIELD_NUMBER = 4;
    private com.futu.openapi.pb.QotUpdatePriceReminder.S2C s2C_;
    /**
     * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
     */
    public boolean hasS2C() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
     */
    public com.futu.openapi.pb.QotUpdatePriceReminder.S2C getS2C() {
      return s2C_ == null ? com.futu.openapi.pb.QotUpdatePriceReminder.S2C.getDefaultInstance() : s2C_;
    }
    /**
     * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
     */
    public com.futu.openapi.pb.QotUpdatePriceReminder.S2COrBuilder getS2COrBuilder() {
      return s2C_ == null ? com.futu.openapi.pb.QotUpdatePriceReminder.S2C.getDefaultInstance() : s2C_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRetType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasS2C()) {
        if (!getS2C().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, getS2C());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, retType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, retMsg_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, errCode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getS2C());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.futu.openapi.pb.QotUpdatePriceReminder.Response)) {
        return super.equals(obj);
      }
      com.futu.openapi.pb.QotUpdatePriceReminder.Response other = (com.futu.openapi.pb.QotUpdatePriceReminder.Response) obj;

      boolean result = true;
      result = result && (hasRetType() == other.hasRetType());
      if (hasRetType()) {
        result = result && (getRetType()
            == other.getRetType());
      }
      result = result && (hasRetMsg() == other.hasRetMsg());
      if (hasRetMsg()) {
        result = result && getRetMsg()
            .equals(other.getRetMsg());
      }
      result = result && (hasErrCode() == other.hasErrCode());
      if (hasErrCode()) {
        result = result && (getErrCode()
            == other.getErrCode());
      }
      result = result && (hasS2C() == other.hasS2C());
      if (hasS2C()) {
        result = result && getS2C()
            .equals(other.getS2C());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRetType()) {
        hash = (37 * hash) + RETTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getRetType();
      }
      if (hasRetMsg()) {
        hash = (37 * hash) + RETMSG_FIELD_NUMBER;
        hash = (53 * hash) + getRetMsg().hashCode();
      }
      if (hasErrCode()) {
        hash = (37 * hash) + ERRCODE_FIELD_NUMBER;
        hash = (53 * hash) + getErrCode();
      }
      if (hasS2C()) {
        hash = (37 * hash) + S2C_FIELD_NUMBER;
        hash = (53 * hash) + getS2C().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.futu.openapi.pb.QotUpdatePriceReminder.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Qot_UpdatePriceReminder.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Qot_UpdatePriceReminder.Response)
        com.futu.openapi.pb.QotUpdatePriceReminder.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.futu.openapi.pb.QotUpdatePriceReminder.internal_static_Qot_UpdatePriceReminder_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.futu.openapi.pb.QotUpdatePriceReminder.internal_static_Qot_UpdatePriceReminder_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.futu.openapi.pb.QotUpdatePriceReminder.Response.class, com.futu.openapi.pb.QotUpdatePriceReminder.Response.Builder.class);
      }

      // Construct using com.futu.openapi.pb.QotUpdatePriceReminder.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getS2CFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        retType_ = -400;
        bitField0_ = (bitField0_ & ~0x00000001);
        retMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        errCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (s2CBuilder_ == null) {
          s2C_ = null;
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.futu.openapi.pb.QotUpdatePriceReminder.internal_static_Qot_UpdatePriceReminder_Response_descriptor;
      }

      public com.futu.openapi.pb.QotUpdatePriceReminder.Response getDefaultInstanceForType() {
        return com.futu.openapi.pb.QotUpdatePriceReminder.Response.getDefaultInstance();
      }

      public com.futu.openapi.pb.QotUpdatePriceReminder.Response build() {
        com.futu.openapi.pb.QotUpdatePriceReminder.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.futu.openapi.pb.QotUpdatePriceReminder.Response buildPartial() {
        com.futu.openapi.pb.QotUpdatePriceReminder.Response result = new com.futu.openapi.pb.QotUpdatePriceReminder.Response(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.retType_ = retType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.retMsg_ = retMsg_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.errCode_ = errCode_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (s2CBuilder_ == null) {
          result.s2C_ = s2C_;
        } else {
          result.s2C_ = s2CBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.futu.openapi.pb.QotUpdatePriceReminder.Response) {
          return mergeFrom((com.futu.openapi.pb.QotUpdatePriceReminder.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.futu.openapi.pb.QotUpdatePriceReminder.Response other) {
        if (other == com.futu.openapi.pb.QotUpdatePriceReminder.Response.getDefaultInstance()) return this;
        if (other.hasRetType()) {
          setRetType(other.getRetType());
        }
        if (other.hasRetMsg()) {
          bitField0_ |= 0x00000002;
          retMsg_ = other.retMsg_;
          onChanged();
        }
        if (other.hasErrCode()) {
          setErrCode(other.getErrCode());
        }
        if (other.hasS2C()) {
          mergeS2C(other.getS2C());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRetType()) {
          return false;
        }
        if (hasS2C()) {
          if (!getS2C().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.futu.openapi.pb.QotUpdatePriceReminder.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.futu.openapi.pb.QotUpdatePriceReminder.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int retType_ = -400;
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public boolean hasRetType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public int getRetType() {
        return retType_;
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder setRetType(int value) {
        bitField0_ |= 0x00000001;
        retType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *RetType,返回结果
       * </pre>
       *
       * <code>required int32 retType = 1 [default = -400];</code>
       */
      public Builder clearRetType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retType_ = -400;
        onChanged();
        return this;
      }

      private java.lang.Object retMsg_ = "";
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public boolean hasRetMsg() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public java.lang.String getRetMsg() {
        java.lang.Object ref = retMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            retMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRetMsgBytes() {
        java.lang.Object ref = retMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          retMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder clearRetMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        retMsg_ = getDefaultInstance().getRetMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string retMsg = 2;</code>
       */
      public Builder setRetMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        retMsg_ = value;
        onChanged();
        return this;
      }

      private int errCode_ ;
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public boolean hasErrCode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public int getErrCode() {
        return errCode_;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder setErrCode(int value) {
        bitField0_ |= 0x00000004;
        errCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 errCode = 3;</code>
       */
      public Builder clearErrCode() {
        bitField0_ = (bitField0_ & ~0x00000004);
        errCode_ = 0;
        onChanged();
        return this;
      }

      private com.futu.openapi.pb.QotUpdatePriceReminder.S2C s2C_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.futu.openapi.pb.QotUpdatePriceReminder.S2C, com.futu.openapi.pb.QotUpdatePriceReminder.S2C.Builder, com.futu.openapi.pb.QotUpdatePriceReminder.S2COrBuilder> s2CBuilder_;
      /**
       * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
       */
      public boolean hasS2C() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
       */
      public com.futu.openapi.pb.QotUpdatePriceReminder.S2C getS2C() {
        if (s2CBuilder_ == null) {
          return s2C_ == null ? com.futu.openapi.pb.QotUpdatePriceReminder.S2C.getDefaultInstance() : s2C_;
        } else {
          return s2CBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
       */
      public Builder setS2C(com.futu.openapi.pb.QotUpdatePriceReminder.S2C value) {
        if (s2CBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          s2C_ = value;
          onChanged();
        } else {
          s2CBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
       */
      public Builder setS2C(
          com.futu.openapi.pb.QotUpdatePriceReminder.S2C.Builder builderForValue) {
        if (s2CBuilder_ == null) {
          s2C_ = builderForValue.build();
          onChanged();
        } else {
          s2CBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
       */
      public Builder mergeS2C(com.futu.openapi.pb.QotUpdatePriceReminder.S2C value) {
        if (s2CBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              s2C_ != null &&
              s2C_ != com.futu.openapi.pb.QotUpdatePriceReminder.S2C.getDefaultInstance()) {
            s2C_ =
              com.futu.openapi.pb.QotUpdatePriceReminder.S2C.newBuilder(s2C_).mergeFrom(value).buildPartial();
          } else {
            s2C_ = value;
          }
          onChanged();
        } else {
          s2CBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
       */
      public Builder clearS2C() {
        if (s2CBuilder_ == null) {
          s2C_ = null;
          onChanged();
        } else {
          s2CBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
       */
      public com.futu.openapi.pb.QotUpdatePriceReminder.S2C.Builder getS2CBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getS2CFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
       */
      public com.futu.openapi.pb.QotUpdatePriceReminder.S2COrBuilder getS2COrBuilder() {
        if (s2CBuilder_ != null) {
          return s2CBuilder_.getMessageOrBuilder();
        } else {
          return s2C_ == null ?
              com.futu.openapi.pb.QotUpdatePriceReminder.S2C.getDefaultInstance() : s2C_;
        }
      }
      /**
       * <code>optional .Qot_UpdatePriceReminder.S2C s2c = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.futu.openapi.pb.QotUpdatePriceReminder.S2C, com.futu.openapi.pb.QotUpdatePriceReminder.S2C.Builder, com.futu.openapi.pb.QotUpdatePriceReminder.S2COrBuilder> 
          getS2CFieldBuilder() {
        if (s2CBuilder_ == null) {
          s2CBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.futu.openapi.pb.QotUpdatePriceReminder.S2C, com.futu.openapi.pb.QotUpdatePriceReminder.S2C.Builder, com.futu.openapi.pb.QotUpdatePriceReminder.S2COrBuilder>(
                  getS2C(),
                  getParentForChildren(),
                  isClean());
          s2C_ = null;
        }
        return s2CBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Qot_UpdatePriceReminder.Response)
    }

    // @@protoc_insertion_point(class_scope:Qot_UpdatePriceReminder.Response)
    private static final com.futu.openapi.pb.QotUpdatePriceReminder.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.futu.openapi.pb.QotUpdatePriceReminder.Response();
    }

    public static com.futu.openapi.pb.QotUpdatePriceReminder.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    public com.futu.openapi.pb.QotUpdatePriceReminder.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdatePriceReminder_S2C_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Qot_UpdatePriceReminder_S2C_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Qot_UpdatePriceReminder_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Qot_UpdatePriceReminder_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035Qot_UpdatePriceReminder.proto\022\027Qot_Upd" +
      "atePriceReminder\032\014Common.proto\032\020Qot_Comm" +
      "on.proto\"\304\001\n\003S2C\022&\n\010security\030\001 \002(\0132\024.Qot" +
      "_Common.Security\022\r\n\005price\030\002 \002(\001\022\022\n\nchang" +
      "eRate\030\003 \002(\001\022\024\n\014marketStatus\030\004 \002(\005\022\017\n\007con" +
      "tent\030\005 \002(\t\022\014\n\004note\030\006 \002(\t\022\013\n\003key\030\007 \001(\003\022\014\n" +
      "\004type\030\010 \001(\005\022\020\n\010setValue\030\t \001(\001\022\020\n\010curValu" +
      "e\030\n \001(\001\"m\n\010Response\022\025\n\007retType\030\001 \002(\005:\004-4" +
      "00\022\016\n\006retMsg\030\002 \001(\t\022\017\n\007errCode\030\003 \001(\005\022)\n\003s" +
      "2c\030\004 \001(\0132\034.Qot_UpdatePriceReminder.S2C*p" +
      "\n\014MarketStatus\022\027\n\023MarketStatus_Unknow\020\000\022" +
      "\025\n\021MarketStatus_Open\020\001\022\026\n\022MarketStatus_U" +
      "SPre\020\002\022\030\n\024MarketStatus_USAfter\020\003BM\n\023com." +
      "futu.openapi.pbZ6github.com/futuopen/fta" +
      "pi4go/pb/qotupdatepricereminder"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.futu.openapi.pb.Common.getDescriptor(),
          com.futu.openapi.pb.QotCommon.getDescriptor(),
        }, assigner);
    internal_static_Qot_UpdatePriceReminder_S2C_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Qot_UpdatePriceReminder_S2C_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Qot_UpdatePriceReminder_S2C_descriptor,
        new java.lang.String[] { "Security", "Price", "ChangeRate", "MarketStatus", "Content", "Note", "Key", "Type", "SetValue", "CurValue", });
    internal_static_Qot_UpdatePriceReminder_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Qot_UpdatePriceReminder_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Qot_UpdatePriceReminder_Response_descriptor,
        new java.lang.String[] { "RetType", "RetMsg", "ErrCode", "S2C", });
    com.futu.openapi.pb.Common.getDescriptor();
    com.futu.openapi.pb.QotCommon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
